// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: services/battle_server.proto

package pb_battle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BattleHandler_BattleSettle_FullMethodName = "/battle.BattleHandler/BattleSettle"
)

// BattleHandlerClient is the client API for BattleHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BattleHandler 战斗结算 RPC — worldmap 行军到达(attack_march)时调用
type BattleHandlerClient interface {
	BattleSettle(ctx context.Context, in *BattleSettleReq, opts ...grpc.CallOption) (*BattleSettleRsp, error)
}

type battleHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewBattleHandlerClient(cc grpc.ClientConnInterface) BattleHandlerClient {
	return &battleHandlerClient{cc}
}

func (c *battleHandlerClient) BattleSettle(ctx context.Context, in *BattleSettleReq, opts ...grpc.CallOption) (*BattleSettleRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BattleSettleRsp)
	err := c.cc.Invoke(ctx, BattleHandler_BattleSettle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BattleHandlerServer is the server API for BattleHandler service.
// All implementations must embed UnimplementedBattleHandlerServer
// for forward compatibility.
//
// BattleHandler 战斗结算 RPC — worldmap 行军到达(attack_march)时调用
type BattleHandlerServer interface {
	BattleSettle(context.Context, *BattleSettleReq) (*BattleSettleRsp, error)
	mustEmbedUnimplementedBattleHandlerServer()
}

// UnimplementedBattleHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBattleHandlerServer struct{}

func (UnimplementedBattleHandlerServer) BattleSettle(context.Context, *BattleSettleReq) (*BattleSettleRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BattleSettle not implemented")
}
func (UnimplementedBattleHandlerServer) mustEmbedUnimplementedBattleHandlerServer() {}
func (UnimplementedBattleHandlerServer) testEmbeddedByValue()                       {}

// UnsafeBattleHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BattleHandlerServer will
// result in compilation errors.
type UnsafeBattleHandlerServer interface {
	mustEmbedUnimplementedBattleHandlerServer()
}

func RegisterBattleHandlerServer(s grpc.ServiceRegistrar, srv BattleHandlerServer) {
	// If the following call pancis, it indicates UnimplementedBattleHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BattleHandler_ServiceDesc, srv)
}

func _BattleHandler_BattleSettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BattleSettleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleHandlerServer).BattleSettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BattleHandler_BattleSettle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BattleHandlerServer).BattleSettle(ctx, req.(*BattleSettleReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BattleHandler_ServiceDesc is the grpc.ServiceDesc for BattleHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BattleHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "battle.BattleHandler",
	HandlerType: (*BattleHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BattleSettle",
			Handler:    _BattleHandler_BattleSettle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/battle_server.proto",
}
