syntax = "proto3";
package pb_game;
option go_package = "server.slg.com/api/protocol/pb/pb_game";

import "common.proto";

service GameService {
    rpc Stream(stream GameServiceNodePacketReq) returns (stream GameServiceNodePacketRsp) {
    }
}

service GameHandler {
    // login server create role
    rpc CreateRole(common.CreateRoleReq) returns (common.CreateRoleRsp);
    rpc LoginOnce(common.LoginOnceReq) returns (common.LoginOnceRsp);

    // Do: unified protocol entry, route by NodePacket.msgId
    rpc Do(common.NodePacket) returns (common.NodePacket);
}

message GameServiceNodePacketReq {
    uint64 roleId            = 1;
    common.NodePacket packet = 2;
}

message GameServiceNodePacketRsp {
    common.NodePacket packet = 1;
}
