// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: city.proto

package pb_city

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildingType 建筑类型（场景建筑 + 角色建筑统一枚举）
// Scene* 前缀 = 地图场景建筑；Role* 前缀 = 角色建造/拥有的建筑
type BuildingType int32

const (
	BuildingType_BuildingNone BuildingType = 0
	// ── 场景建筑（地图上生成） ──
	BuildingType_SceneUrbanArea  BuildingType = 1 // 城区
	BuildingType_SceneCityCenter BuildingType = 2 // 城中心
	BuildingType_ScenePass       BuildingType = 3 // 关隘
	BuildingType_SceneFortress   BuildingType = 4 // 要塞
	// ── 角色建筑（角色建造/拥有） ──
	BuildingType_RoleMainCity   BuildingType = 101 // 主城
	BuildingType_RoleBranchCity BuildingType = 102 // 分城
	BuildingType_RoleMilitary   BuildingType = 103 // 军事建筑
	BuildingType_RoleBarracks   BuildingType = 104 // 兵营（兵力上限加成，归属城市）
)

// Enum value maps for BuildingType.
var (
	BuildingType_name = map[int32]string{
		0:   "BuildingNone",
		1:   "SceneUrbanArea",
		2:   "SceneCityCenter",
		3:   "ScenePass",
		4:   "SceneFortress",
		101: "RoleMainCity",
		102: "RoleBranchCity",
		103: "RoleMilitary",
		104: "RoleBarracks",
	}
	BuildingType_value = map[string]int32{
		"BuildingNone":    0,
		"SceneUrbanArea":  1,
		"SceneCityCenter": 2,
		"ScenePass":       3,
		"SceneFortress":   4,
		"RoleMainCity":    101,
		"RoleBranchCity":  102,
		"RoleMilitary":    103,
		"RoleBarracks":    104,
	}
)

func (x BuildingType) Enum() *BuildingType {
	p := new(BuildingType)
	*p = x
	return p
}

func (x BuildingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildingType) Descriptor() protoreflect.EnumDescriptor {
	return file_city_proto_enumTypes[0].Descriptor()
}

func (BuildingType) Type() protoreflect.EnumType {
	return &file_city_proto_enumTypes[0]
}

func (x BuildingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildingType.Descriptor instead.
func (BuildingType) EnumDescriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{0}
}

// BuildingFootprint 建筑占地（格数）
type BuildingFootprint int32

const (
	BuildingFootprint_Footprint_None BuildingFootprint = 0
	BuildingFootprint_Footprint4     BuildingFootprint = 4 // 2×2
	BuildingFootprint_Footprint9     BuildingFootprint = 9 // 3×3
)

// Enum value maps for BuildingFootprint.
var (
	BuildingFootprint_name = map[int32]string{
		0: "Footprint_None",
		4: "Footprint4",
		9: "Footprint9",
	}
	BuildingFootprint_value = map[string]int32{
		"Footprint_None": 0,
		"Footprint4":     4,
		"Footprint9":     9,
	}
)

func (x BuildingFootprint) Enum() *BuildingFootprint {
	p := new(BuildingFootprint)
	*p = x
	return p
}

func (x BuildingFootprint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildingFootprint) Descriptor() protoreflect.EnumDescriptor {
	return file_city_proto_enumTypes[1].Descriptor()
}

func (BuildingFootprint) Type() protoreflect.EnumType {
	return &file_city_proto_enumTypes[1]
}

func (x BuildingFootprint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildingFootprint.Descriptor instead.
func (BuildingFootprint) EnumDescriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{1}
}

// BuildingState 建筑状态
type BuildingState int32

const (
	BuildingState_None         BuildingState = 0 // 无效
	BuildingState_Constructing BuildingState = 1 // 建设中
	BuildingState_Completed    BuildingState = 2 // 已完成
)

// Enum value maps for BuildingState.
var (
	BuildingState_name = map[int32]string{
		0: "None",
		1: "Constructing",
		2: "Completed",
	}
	BuildingState_value = map[string]int32{
		"None":         0,
		"Constructing": 1,
		"Completed":    2,
	}
)

func (x BuildingState) Enum() *BuildingState {
	p := new(BuildingState)
	*p = x
	return p
}

func (x BuildingState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildingState) Descriptor() protoreflect.EnumDescriptor {
	return file_city_proto_enumTypes[2].Descriptor()
}

func (BuildingState) Type() protoreflect.EnumType {
	return &file_city_proto_enumTypes[2]
}

func (x BuildingState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildingState.Descriptor instead.
func (BuildingState) EnumDescriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{2}
}

// FirstOccRecordData 首占记录数据
type FirstOccRecordData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName    string `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`           // 记录名称
	RecordScore uint64 `protobuf:"varint,2,opt,name=record_score,json=recordScore,proto3" json:"record_score,omitempty"` // 记录得分
	Rank        int32  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`                                  // 记录排名
}

func (x *FirstOccRecordData) Reset() {
	*x = FirstOccRecordData{}
	mi := &file_city_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirstOccRecordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstOccRecordData) ProtoMessage() {}

func (x *FirstOccRecordData) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstOccRecordData.ProtoReflect.Descriptor instead.
func (*FirstOccRecordData) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{0}
}

func (x *FirstOccRecordData) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *FirstOccRecordData) GetRecordScore() uint64 {
	if x != nil {
		return x.RecordScore
	}
	return 0
}

func (x *FirstOccRecordData) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// CityFirstOccRecord 城市首占记录
type CityFirstOccRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OccUnionId             uint64                `protobuf:"varint,1,opt,name=occ_union_id,json=occUnionId,proto3" json:"occ_union_id,omitempty"`                                      // 占领联盟id
	OccUnionName           string                `protobuf:"bytes,2,opt,name=occ_union_name,json=occUnionName,proto3" json:"occ_union_name,omitempty"`                                 // 占领联盟名称
	KillGarrisonRecordData []*FirstOccRecordData `protobuf:"bytes,3,rep,name=kill_garrison_record_data,json=killGarrisonRecordData,proto3" json:"kill_garrison_record_data,omitempty"` // 记录数据
	DemolitionRecordData   []*FirstOccRecordData `protobuf:"bytes,4,rep,name=demolition_record_data,json=demolitionRecordData,proto3" json:"demolition_record_data,omitempty"`         // 记录数据
}

func (x *CityFirstOccRecord) Reset() {
	*x = CityFirstOccRecord{}
	mi := &file_city_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityFirstOccRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityFirstOccRecord) ProtoMessage() {}

func (x *CityFirstOccRecord) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityFirstOccRecord.ProtoReflect.Descriptor instead.
func (*CityFirstOccRecord) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{1}
}

func (x *CityFirstOccRecord) GetOccUnionId() uint64 {
	if x != nil {
		return x.OccUnionId
	}
	return 0
}

func (x *CityFirstOccRecord) GetOccUnionName() string {
	if x != nil {
		return x.OccUnionName
	}
	return ""
}

func (x *CityFirstOccRecord) GetKillGarrisonRecordData() []*FirstOccRecordData {
	if x != nil {
		return x.KillGarrisonRecordData
	}
	return nil
}

func (x *CityFirstOccRecord) GetDemolitionRecordData() []*FirstOccRecordData {
	if x != nil {
		return x.DemolitionRecordData
	}
	return nil
}

type CityData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CityData) Reset() {
	*x = CityData{}
	mi := &file_city_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityData) ProtoMessage() {}

func (x *CityData) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityData.ProtoReflect.Descriptor instead.
func (*CityData) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{2}
}

// RoleBuildingInfo 角色建筑信息
type RoleBuildingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                           // 建筑ID
	Type      BuildingType      `protobuf:"varint,2,opt,name=type,proto3,enum=city.BuildingType" json:"type,omitempty"`                // 类型（场景/角色建筑统一枚举）
	Footprint BuildingFootprint `protobuf:"varint,3,opt,name=footprint,proto3,enum=city.BuildingFootprint" json:"footprint,omitempty"` // 占地
	MapId     int32             `protobuf:"varint,4,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`                        // 中心格
	Level     uint32            `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	State     BuildingState     `protobuf:"varint,6,opt,name=state,proto3,enum=city.BuildingState" json:"state,omitempty"` // 建筑状态
	CityId    uint64            `protobuf:"varint,7,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`         // 归属城市（兵营等附属建筑）
}

func (x *RoleBuildingInfo) Reset() {
	*x = RoleBuildingInfo{}
	mi := &file_city_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBuildingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBuildingInfo) ProtoMessage() {}

func (x *RoleBuildingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBuildingInfo.ProtoReflect.Descriptor instead.
func (*RoleBuildingInfo) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{3}
}

func (x *RoleBuildingInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleBuildingInfo) GetType() BuildingType {
	if x != nil {
		return x.Type
	}
	return BuildingType_BuildingNone
}

func (x *RoleBuildingInfo) GetFootprint() BuildingFootprint {
	if x != nil {
		return x.Footprint
	}
	return BuildingFootprint_Footprint_None
}

func (x *RoleBuildingInfo) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *RoleBuildingInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleBuildingInfo) GetState() BuildingState {
	if x != nil {
		return x.State
	}
	return BuildingState_None
}

func (x *RoleBuildingInfo) GetCityId() uint64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

// 建造建筑（主城/分城/军事建筑/兵营）
type BuildingBuildReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   BuildingType `protobuf:"varint,1,opt,name=type,proto3,enum=city.BuildingType" json:"type,omitempty"` // 角色建筑类型（RoleMainCity/BranchCity/Military/Barracks）
	MapId  int32        `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`         // 放置的中心格
	CityId uint64       `protobuf:"varint,3,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`      // 归属城市ID（兵营等附属建筑；主城/分城默认 0）
}

func (x *BuildingBuildReq) Reset() {
	*x = BuildingBuildReq{}
	mi := &file_city_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingBuildReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingBuildReq) ProtoMessage() {}

func (x *BuildingBuildReq) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingBuildReq.ProtoReflect.Descriptor instead.
func (*BuildingBuildReq) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{4}
}

func (x *BuildingBuildReq) GetType() BuildingType {
	if x != nil {
		return x.Type
	}
	return BuildingType_BuildingNone
}

func (x *BuildingBuildReq) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *BuildingBuildReq) GetCityId() uint64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

type BuildingBuildResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Building *RoleBuildingInfo `protobuf:"bytes,1,opt,name=building,proto3" json:"building,omitempty"`
}

func (x *BuildingBuildResp) Reset() {
	*x = BuildingBuildResp{}
	mi := &file_city_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingBuildResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingBuildResp) ProtoMessage() {}

func (x *BuildingBuildResp) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingBuildResp.ProtoReflect.Descriptor instead.
func (*BuildingBuildResp) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{5}
}

func (x *BuildingBuildResp) GetBuilding() *RoleBuildingInfo {
	if x != nil {
		return x.Building
	}
	return nil
}

// 查询建筑列表
type BuildingListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BuildingListReq) Reset() {
	*x = BuildingListReq{}
	mi := &file_city_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingListReq) ProtoMessage() {}

func (x *BuildingListReq) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingListReq.ProtoReflect.Descriptor instead.
func (*BuildingListReq) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{6}
}

type BuildingListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buildings []*RoleBuildingInfo `protobuf:"bytes,1,rep,name=buildings,proto3" json:"buildings,omitempty"`
}

func (x *BuildingListResp) Reset() {
	*x = BuildingListResp{}
	mi := &file_city_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildingListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingListResp) ProtoMessage() {}

func (x *BuildingListResp) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingListResp.ProtoReflect.Descriptor instead.
func (*BuildingListResp) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{7}
}

func (x *BuildingListResp) GetBuildings() []*RoleBuildingInfo {
	if x != nil {
		return x.Buildings
	}
	return nil
}

var File_city_proto protoreflect.FileDescriptor

var file_city_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x22, 0x68, 0x0a, 0x12, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x81, 0x02, 0x0a,
	0x12, 0x43, 0x69, 0x74, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6f, 0x63, 0x63, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x63, 0x63, 0x5f, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f,
	0x63, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x53, 0x0a, 0x19, 0x6b,
	0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x61, 0x72, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x16, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x61,
	0x72, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x4e, 0x0a, 0x16, 0x64, 0x65, 0x6d, 0x6f, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x64, 0x65, 0x6d, 0x6f,
	0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x0a, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x22, 0xf2, 0x01, 0x0a,
	0x10, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x66, 0x6f, 0x6f,
	0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x6f, 0x74,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x52, 0x09, 0x66, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x29, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63,
	0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x22, 0x6a, 0x0a, 0x10, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a,
	0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x61, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x47, 0x0a,
	0x11, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x11, 0x0a, 0x0f, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x48, 0x0a, 0x10, 0x42, 0x75, 0x69,
	0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x34, 0x0a,
	0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x75, 0x69, 0x6c,
	0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x73, 0x2a, 0xb5, 0x01, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x55,
	0x72, 0x62, 0x61, 0x6e, 0x41, 0x72, 0x65, 0x61, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x63,
	0x65, 0x6e, 0x65, 0x43, 0x69, 0x74, 0x79, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x10, 0x02, 0x12,
	0x0d, 0x0a, 0x09, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x50, 0x61, 0x73, 0x73, 0x10, 0x03, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x46, 0x6f, 0x72, 0x74, 0x72, 0x65, 0x73, 0x73, 0x10,
	0x04, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x4d, 0x61, 0x69, 0x6e, 0x43, 0x69, 0x74,
	0x79, 0x10, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x72, 0x61, 0x6e, 0x63,
	0x68, 0x43, 0x69, 0x74, 0x79, 0x10, 0x66, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x6f, 0x6c, 0x65, 0x4d,
	0x69, 0x6c, 0x69, 0x74, 0x61, 0x72, 0x79, 0x10, 0x67, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x6f, 0x6c,
	0x65, 0x42, 0x61, 0x72, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x10, 0x68, 0x2a, 0x47, 0x0a, 0x11, 0x42,
	0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x0e, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x5f, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x34, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x6f, 0x6f, 0x74, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x39, 0x10, 0x09, 0x2a, 0x3a, 0x0a, 0x0d, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x02,
	0x42, 0x28, 0x5a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f,
	0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_city_proto_rawDescOnce sync.Once
	file_city_proto_rawDescData = file_city_proto_rawDesc
)

func file_city_proto_rawDescGZIP() []byte {
	file_city_proto_rawDescOnce.Do(func() {
		file_city_proto_rawDescData = protoimpl.X.CompressGZIP(file_city_proto_rawDescData)
	})
	return file_city_proto_rawDescData
}

var file_city_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_city_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_city_proto_goTypes = []any{
	(BuildingType)(0),          // 0: city.BuildingType
	(BuildingFootprint)(0),     // 1: city.BuildingFootprint
	(BuildingState)(0),         // 2: city.BuildingState
	(*FirstOccRecordData)(nil), // 3: city.FirstOccRecordData
	(*CityFirstOccRecord)(nil), // 4: city.CityFirstOccRecord
	(*CityData)(nil),           // 5: city.CityData
	(*RoleBuildingInfo)(nil),   // 6: city.RoleBuildingInfo
	(*BuildingBuildReq)(nil),   // 7: city.BuildingBuildReq
	(*BuildingBuildResp)(nil),  // 8: city.BuildingBuildResp
	(*BuildingListReq)(nil),    // 9: city.BuildingListReq
	(*BuildingListResp)(nil),   // 10: city.BuildingListResp
}
var file_city_proto_depIdxs = []int32{
	3, // 0: city.CityFirstOccRecord.kill_garrison_record_data:type_name -> city.FirstOccRecordData
	3, // 1: city.CityFirstOccRecord.demolition_record_data:type_name -> city.FirstOccRecordData
	0, // 2: city.RoleBuildingInfo.type:type_name -> city.BuildingType
	1, // 3: city.RoleBuildingInfo.footprint:type_name -> city.BuildingFootprint
	2, // 4: city.RoleBuildingInfo.state:type_name -> city.BuildingState
	0, // 5: city.BuildingBuildReq.type:type_name -> city.BuildingType
	6, // 6: city.BuildingBuildResp.building:type_name -> city.RoleBuildingInfo
	6, // 7: city.BuildingListResp.buildings:type_name -> city.RoleBuildingInfo
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_city_proto_init() }
func file_city_proto_init() {
	if File_city_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_city_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_city_proto_goTypes,
		DependencyIndexes: file_city_proto_depIdxs,
		EnumInfos:         file_city_proto_enumTypes,
		MessageInfos:      file_city_proto_msgTypes,
	}.Build()
	File_city_proto = out.File
	file_city_proto_rawDesc = nil
	file_city_proto_goTypes = nil
	file_city_proto_depIdxs = nil
}
