// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: city.proto

package pb_city

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BuildingType 建筑类型
type BuildingType int32

const (
	BuildingType_None       BuildingType = 0
	BuildingType_UrbanArea  BuildingType = 1 // 城区
	BuildingType_CityCenter BuildingType = 2 // 城中心
	BuildingType_Pass       BuildingType = 3 // 关隘
	BuildingType_Fortress   BuildingType = 4 // 要塞
)

// Enum value maps for BuildingType.
var (
	BuildingType_name = map[int32]string{
		0: "None",
		1: "UrbanArea",
		2: "CityCenter",
		3: "Pass",
		4: "Fortress",
	}
	BuildingType_value = map[string]int32{
		"None":       0,
		"UrbanArea":  1,
		"CityCenter": 2,
		"Pass":       3,
		"Fortress":   4,
	}
)

func (x BuildingType) Enum() *BuildingType {
	p := new(BuildingType)
	*p = x
	return p
}

func (x BuildingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildingType) Descriptor() protoreflect.EnumDescriptor {
	return file_city_proto_enumTypes[0].Descriptor()
}

func (BuildingType) Type() protoreflect.EnumType {
	return &file_city_proto_enumTypes[0]
}

func (x BuildingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildingType.Descriptor instead.
func (BuildingType) EnumDescriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{0}
}

// FirstOccRecordData 首占记录数据
type FirstOccRecordData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleName    string `protobuf:"util_bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`           // 记录名称
	RecordScore uint64 `protobuf:"varint,2,opt,name=record_score,json=recordScore,proto3" json:"record_score,omitempty"` // 记录得分
	Rank        int32  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`                                  // 记录排名
}

func (x *FirstOccRecordData) Reset() {
	*x = FirstOccRecordData{}
	mi := &file_city_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirstOccRecordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstOccRecordData) ProtoMessage() {}

func (x *FirstOccRecordData) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstOccRecordData.ProtoReflect.Descriptor instead.
func (*FirstOccRecordData) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{0}
}

func (x *FirstOccRecordData) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *FirstOccRecordData) GetRecordScore() uint64 {
	if x != nil {
		return x.RecordScore
	}
	return 0
}

func (x *FirstOccRecordData) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// CityFirstOccRecord 城市首占记录
type CityFirstOccRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OccUnionId             uint64                `protobuf:"varint,1,opt,name=occ_union_id,json=occUnionId,proto3" json:"occ_union_id,omitempty"`                                      // 占领联盟id
	OccUnionName           string                `protobuf:"util_bytes,2,opt,name=occ_union_name,json=occUnionName,proto3" json:"occ_union_name,omitempty"`                                 // 占领联盟名称
	KillGarrisonRecordData []*FirstOccRecordData `protobuf:"util_bytes,3,rep,name=kill_garrison_record_data,json=killGarrisonRecordData,proto3" json:"kill_garrison_record_data,omitempty"` // 记录数据
	DemolitionRecordData   []*FirstOccRecordData `protobuf:"util_bytes,4,rep,name=demolition_record_data,json=demolitionRecordData,proto3" json:"demolition_record_data,omitempty"`         // 记录数据
}

func (x *CityFirstOccRecord) Reset() {
	*x = CityFirstOccRecord{}
	mi := &file_city_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityFirstOccRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityFirstOccRecord) ProtoMessage() {}

func (x *CityFirstOccRecord) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityFirstOccRecord.ProtoReflect.Descriptor instead.
func (*CityFirstOccRecord) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{1}
}

func (x *CityFirstOccRecord) GetOccUnionId() uint64 {
	if x != nil {
		return x.OccUnionId
	}
	return 0
}

func (x *CityFirstOccRecord) GetOccUnionName() string {
	if x != nil {
		return x.OccUnionName
	}
	return ""
}

func (x *CityFirstOccRecord) GetKillGarrisonRecordData() []*FirstOccRecordData {
	if x != nil {
		return x.KillGarrisonRecordData
	}
	return nil
}

func (x *CityFirstOccRecord) GetDemolitionRecordData() []*FirstOccRecordData {
	if x != nil {
		return x.DemolitionRecordData
	}
	return nil
}

type CityData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CityData) Reset() {
	*x = CityData{}
	mi := &file_city_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityData) ProtoMessage() {}

func (x *CityData) ProtoReflect() protoreflect.Message {
	mi := &file_city_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityData.ProtoReflect.Descriptor instead.
func (*CityData) Descriptor() ([]byte, []int) {
	return file_city_proto_rawDescGZIP(), []int{2}
}

var File_city_proto protoreflect.FileDescriptor

var file_city_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x22, 0x68, 0x0a, 0x12, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x22, 0x81, 0x02, 0x0a,
	0x12, 0x43, 0x69, 0x74, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x6f, 0x63, 0x63, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6f, 0x63, 0x63, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x6f, 0x63, 0x63, 0x5f, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f,
	0x63, 0x63, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x53, 0x0a, 0x19, 0x6b,
	0x69, 0x6c, 0x6c, 0x5f, 0x67, 0x61, 0x72, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x16, 0x6b, 0x69, 0x6c, 0x6c, 0x47, 0x61,
	0x72, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x4e, 0x0a, 0x16, 0x64, 0x65, 0x6d, 0x6f, 0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4f, 0x63, 0x63,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x64, 0x65, 0x6d, 0x6f,
	0x6c, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x0a, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x4f, 0x0a, 0x0c,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x72, 0x62, 0x61, 0x6e, 0x41,
	0x72, 0x65, 0x61, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x69, 0x74, 0x79, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x10, 0x03, 0x12,
	0x0c, 0x0a, 0x08, 0x46, 0x6f, 0x72, 0x74, 0x72, 0x65, 0x73, 0x73, 0x10, 0x04, 0x42, 0x28, 0x5a,
	0x26, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f,
	0x70, 0x62, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_city_proto_rawDescOnce sync.Once
	file_city_proto_rawDescData = file_city_proto_rawDesc
)

func file_city_proto_rawDescGZIP() []byte {
	file_city_proto_rawDescOnce.Do(func() {
		file_city_proto_rawDescData = protoimpl.X.CompressGZIP(file_city_proto_rawDescData)
	})
	return file_city_proto_rawDescData
}

var file_city_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_city_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_city_proto_goTypes = []any{
	(BuildingType)(0),          // 0: city.BuildingType
	(*FirstOccRecordData)(nil), // 1: city.FirstOccRecordData
	(*CityFirstOccRecord)(nil), // 2: city.CityFirstOccRecord
	(*CityData)(nil),           // 3: city.CityData
}
var file_city_proto_depIdxs = []int32{
	1, // 0: city.CityFirstOccRecord.kill_garrison_record_data:type_name -> city.FirstOccRecordData
	1, // 1: city.CityFirstOccRecord.demolition_record_data:type_name -> city.FirstOccRecordData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_city_proto_init() }
func file_city_proto_init() {
	if File_city_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_city_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_city_proto_goTypes,
		DependencyIndexes: file_city_proto_depIdxs,
		EnumInfos:         file_city_proto_enumTypes,
		MessageInfos:      file_city_proto_msgTypes,
	}.Build()
	File_city_proto = out.File
	file_city_proto_rawDesc = nil
	file_city_proto_goTypes = nil
	file_city_proto_depIdxs = nil
}
