// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: camera.proto

package pb_camera

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_city "server.slg.com/api/protocol/pb/pb_city"
	pb_maps_march "server.slg.com/api/protocol/pb/pb_maps_march"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraLayer int32

const (
	CameraLayer_Layer0 CameraLayer = 0
)

// Enum value maps for CameraLayer.
var (
	CameraLayer_name = map[int32]string{
		0: "Layer0",
	}
	CameraLayer_value = map[string]int32{
		"Layer0": 0,
	}
)

func (x CameraLayer) Enum() *CameraLayer {
	p := new(CameraLayer)
	*p = x
	return p
}

func (x CameraLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CameraLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_camera_proto_enumTypes[0].Descriptor()
}

func (CameraLayer) Type() protoreflect.EnumType {
	return &file_camera_proto_enumTypes[0]
}

func (x CameraLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CameraLayer.Descriptor instead.
func (CameraLayer) EnumDescriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{0}
}

// MapInfo 地图数据
type MapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId     int32             `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`             // 地图ID
	ServerId  uint32            `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`    // 服务器ID
	LandCover int32             `protobuf:"varint,3,opt,name=land_cover,json=landCover,proto3" json:"land_cover,omitempty"` // 占地范围
	RoleId    uint64            `protobuf:"varint,4,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`          // 角色ID
	UnionId   uint64            `protobuf:"varint,5,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`       // 联盟id
	City      *pb_city.CityData `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`                            // 城数据
}

func (x *MapInfo) Reset() {
	*x = MapInfo{}
	mi := &file_camera_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfo) ProtoMessage() {}

func (x *MapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfo.ProtoReflect.Descriptor instead.
func (*MapInfo) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{0}
}

func (x *MapInfo) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapInfo) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *MapInfo) GetLandCover() int32 {
	if x != nil {
		return x.LandCover
	}
	return 0
}

func (x *MapInfo) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MapInfo) GetUnionId() uint64 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

func (x *MapInfo) GetCity() *pb_city.CityData {
	if x != nil {
		return x.City
	}
	return nil
}

// 初始化镜头, 42200
type CameraInitReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID uint32 `protobuf:"varint,1,opt,name=serverID,proto3" json:"serverID,omitempty"` // 镜头需要查看的服务器ID
}

func (x *CameraInitReq) Reset() {
	*x = CameraInitReq{}
	mi := &file_camera_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInitReq) ProtoMessage() {}

func (x *CameraInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInitReq.ProtoReflect.Descriptor instead.
func (*CameraInitReq) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{1}
}

func (x *CameraInitReq) GetServerID() uint32 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

type CameraInitResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GridWidth  uint32                     `protobuf:"varint,1,opt,name=gridWidth,proto3" json:"gridWidth,omitempty"`   // 格子div宽度
	GridHeight uint32                     `protobuf:"varint,2,opt,name=gridHeight,proto3" json:"gridHeight,omitempty"` // 格子div高度
	March      []*pb_maps_march.MarchInfo `protobuf:"bytes,3,rep,name=march,proto3" json:"march,omitempty"`            // 本人的行军数据
}

func (x *CameraInitResp) Reset() {
	*x = CameraInitResp{}
	mi := &file_camera_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraInitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraInitResp) ProtoMessage() {}

func (x *CameraInitResp) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraInitResp.ProtoReflect.Descriptor instead.
func (*CameraInitResp) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{2}
}

func (x *CameraInitResp) GetGridWidth() uint32 {
	if x != nil {
		return x.GridWidth
	}
	return 0
}

func (x *CameraInitResp) GetGridHeight() uint32 {
	if x != nil {
		return x.GridHeight
	}
	return 0
}

func (x *CameraInitResp) GetMarch() []*pb_maps_march.MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

// 镜头移动, 42202
type CameraMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"` // x坐标
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"` // y坐标
}

func (x *CameraMoveReq) Reset() {
	*x = CameraMoveReq{}
	mi := &file_camera_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraMoveReq) ProtoMessage() {}

func (x *CameraMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraMoveReq.ProtoReflect.Descriptor instead.
func (*CameraMoveReq) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{3}
}

func (x *CameraMoveReq) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CameraMoveReq) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type CameraMoveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Map              []*MapInfo                 `protobuf:"bytes,1,rep,name=map,proto3" json:"map,omitempty"`                                                               // 地图数据
	March            []*pb_maps_march.MarchInfo `protobuf:"bytes,2,rep,name=march,proto3" json:"march,omitempty"`                                                           // 行军数据
	DeleteScreenId   []uint32                   `protobuf:"varint,3,rep,packed,name=delete_screen_id,json=deleteScreenId,proto3" json:"delete_screen_id,omitempty"`         // 删除的视野块ID
	UnionMemberMapId []int32                    `protobuf:"varint,4,rep,packed,name=union_member_map_id,json=unionMemberMapId,proto3" json:"union_member_map_id,omitempty"` // 盟友地图ID(只会在3级视野返回)
}

func (x *CameraMoveResp) Reset() {
	*x = CameraMoveResp{}
	mi := &file_camera_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraMoveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraMoveResp) ProtoMessage() {}

func (x *CameraMoveResp) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraMoveResp.ProtoReflect.Descriptor instead.
func (*CameraMoveResp) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{4}
}

func (x *CameraMoveResp) GetMap() []*MapInfo {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *CameraMoveResp) GetMarch() []*pb_maps_march.MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

func (x *CameraMoveResp) GetDeleteScreenId() []uint32 {
	if x != nil {
		return x.DeleteScreenId
	}
	return nil
}

func (x *CameraMoveResp) GetUnionMemberMapId() []int32 {
	if x != nil {
		return x.UnionMemberMapId
	}
	return nil
}

// ---------------------------------------//
type PushMapInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapInfos []*MapInfo `protobuf:"bytes,1,rep,name=map_infos,json=mapInfos,proto3" json:"map_infos,omitempty"` // 地图数据
}

func (x *PushMapInfo) Reset() {
	*x = PushMapInfo{}
	mi := &file_camera_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMapInfo) ProtoMessage() {}

func (x *PushMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_camera_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMapInfo.ProtoReflect.Descriptor instead.
func (*PushMapInfo) Descriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{5}
}

func (x *PushMapInfo) GetMapInfos() []*MapInfo {
	if x != nil {
		return x.MapInfos
	}
	return nil
}

var File_camera_proto protoreflect.FileDescriptor

var file_camera_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x1a, 0x0b, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb4, 0x01, 0x0a, 0x07, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x61, 0x6e, 0x64, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0x2b, 0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x7b, 0x0a, 0x0e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x49, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x69, 0x64, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x67, 0x72, 0x69, 0x64, 0x57, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x69, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x67, 0x72, 0x69, 0x64, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x70, 0x73, 0x2e, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x4d, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6d, 0x61, 0x72, 0x63, 0x68,
	0x22, 0x2b, 0x0a, 0x0d, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0xb9, 0x01,
	0x0a, 0x0e, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x21, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03,
	0x6d, 0x61, 0x70, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x70, 0x73, 0x2e, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x2e,
	0x4d, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6d, 0x61, 0x72, 0x63, 0x68,
	0x12, 0x28, 0x0a, 0x10, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x73, 0x63, 0x72, 0x65, 0x65,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x13, 0x75, 0x6e,
	0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x10, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x0b, 0x50, 0x75, 0x73,
	0x68, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x09, 0x6d, 0x61, 0x70, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x2e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6d, 0x61,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x2a, 0x19, 0x0a, 0x0b, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x30, 0x10,
	0x00, 0x42, 0x2a, 0x5a, 0x28, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_camera_proto_rawDescOnce sync.Once
	file_camera_proto_rawDescData = file_camera_proto_rawDesc
)

func file_camera_proto_rawDescGZIP() []byte {
	file_camera_proto_rawDescOnce.Do(func() {
		file_camera_proto_rawDescData = protoimpl.X.CompressGZIP(file_camera_proto_rawDescData)
	})
	return file_camera_proto_rawDescData
}

var file_camera_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_camera_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_camera_proto_goTypes = []any{
	(CameraLayer)(0),                // 0: camera.CameraLayer
	(*MapInfo)(nil),                 // 1: camera.MapInfo
	(*CameraInitReq)(nil),           // 2: camera.CameraInitReq
	(*CameraInitResp)(nil),          // 3: camera.CameraInitResp
	(*CameraMoveReq)(nil),           // 4: camera.CameraMoveReq
	(*CameraMoveResp)(nil),          // 5: camera.CameraMoveResp
	(*PushMapInfo)(nil),             // 6: camera.PushMapInfo
	(*pb_city.CityData)(nil),        // 7: city.CityData
	(*pb_maps_march.MarchInfo)(nil), // 8: maps.march.MarchInfo
}
var file_camera_proto_depIdxs = []int32{
	7, // 0: camera.MapInfo.city:type_name -> city.CityData
	8, // 1: camera.CameraInitResp.march:type_name -> maps.march.MarchInfo
	1, // 2: camera.CameraMoveResp.map:type_name -> camera.MapInfo
	8, // 3: camera.CameraMoveResp.march:type_name -> maps.march.MarchInfo
	1, // 4: camera.PushMapInfo.map_infos:type_name -> camera.MapInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_camera_proto_init() }
func file_camera_proto_init() {
	if File_camera_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camera_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_camera_proto_goTypes,
		DependencyIndexes: file_camera_proto_depIdxs,
		EnumInfos:         file_camera_proto_enumTypes,
		MessageInfos:      file_camera_proto_msgTypes,
	}.Build()
	File_camera_proto = out.File
	file_camera_proto_rawDesc = nil
	file_camera_proto_goTypes = nil
	file_camera_proto_depIdxs = nil
}
