// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.21.8
// source: camera.proto

package pb_camera

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CameraLayer int32

const (
	CameraLayer_Layer0 CameraLayer = 0
)

// Enum value maps for CameraLayer.
var (
	CameraLayer_name = map[int32]string{
		0: "Layer0",
	}
	CameraLayer_value = map[string]int32{
		"Layer0": 0,
	}
)

func (x CameraLayer) Enum() *CameraLayer {
	p := new(CameraLayer)
	*p = x
	return p
}

func (x CameraLayer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CameraLayer) Descriptor() protoreflect.EnumDescriptor {
	return file_camera_proto_enumTypes[0].Descriptor()
}

func (CameraLayer) Type() protoreflect.EnumType {
	return &file_camera_proto_enumTypes[0]
}

func (x CameraLayer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CameraLayer.Descriptor instead.
func (CameraLayer) EnumDescriptor() ([]byte, []int) {
	return file_camera_proto_rawDescGZIP(), []int{0}
}

var File_camera_proto protoreflect.FileDescriptor

var file_camera_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x2a, 0x19, 0x0a, 0x0b, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x30, 0x10,
	0x00, 0x42, 0x2a, 0x5a, 0x28, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x63, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_camera_proto_rawDescOnce sync.Once
	file_camera_proto_rawDescData = file_camera_proto_rawDesc
)

func file_camera_proto_rawDescGZIP() []byte {
	file_camera_proto_rawDescOnce.Do(func() {
		file_camera_proto_rawDescData = protoimpl.X.CompressGZIP(file_camera_proto_rawDescData)
	})
	return file_camera_proto_rawDescData
}

var file_camera_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_camera_proto_goTypes = []any{
	(CameraLayer)(0), // 0: camera.CameraLayer
}
var file_camera_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_camera_proto_init() }
func file_camera_proto_init() {
	if File_camera_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_camera_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_camera_proto_goTypes,
		DependencyIndexes: file_camera_proto_depIdxs,
		EnumInfos:         file_camera_proto_enumTypes,
	}.Build()
	File_camera_proto = out.File
	file_camera_proto_rawDesc = nil
	file_camera_proto_goTypes = nil
	file_camera_proto_depIdxs = nil
}
