package main

import (
	"flag"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
)

// ClientInfo describes one generated gRPC client from a *_grpc.pb.go file.
type ClientInfo struct {
	ClientType string // GameServiceClient
	FieldName  string // gameServiceClient
	PkgAlias   string // pb_game
	ImportPath string // server.slg.com/api/protocol/pb/pb_game
	NodeType   string // NodeGameService
}

// ImportInfo describes a single Go import line.
type ImportInfo struct {
	Alias string
	Path  string
}

// TemplateData is the data passed to the code-generation template.
type TemplateData struct {
	PackageName string
	Imports     []ImportInfo
	Clients     []ClientInfo
}

var clientRe = regexp.MustCompile(`func New(\w+Client)\(cc grpc\.ClientConnInterface\)`)

// pkgNodeMap pb_xxx package → etcd NodeService 常量名映射。
// 新增 proto service 后如果生成的 nodeType 不对，在这里加一行。
var pkgNodeMap = map[string]string{
	"pb_game":     "NodeGameService",
	"pb_gateway":  "NodeGatewayService",
	"pb_worldmap": "NodeWorldMapService",
}

func main() {
	pbDir := flag.String("pb-dir", "api/protocol/pb", "pb 目录（相对于 module root）")
	output := flag.String("output", "common/conns/rpcconn/rpc_conns/rpc.client.handler.gen.go", "输出文件路径")
	root := flag.String("root", ".", "Go module 根目录")
	pkgName := flag.String("package", "rpc_conns", "输出文件的 Go package 名")
	flag.Parse()

	absRoot, err := filepath.Abs(*root)
	if err != nil {
		die("获取绝对路径失败: %v", err)
	}
	modulePath := readModulePath(absRoot)
	if modulePath == "" {
		die("无法从 go.mod 中读取 module path")
	}

	absPbDir := filepath.Join(absRoot, *pbDir)
	if fi, err := os.Stat(absPbDir); err != nil || !fi.IsDir() {
		die("pb-dir 不存在或不是目录: %s", absPbDir)
	}

	var clients []ClientInfo
	importSet := make(map[string]string)

	if err := filepath.Walk(absPbDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(path, "_grpc.pb.go") {
			return nil
		}

		pkgAlias := extractPackageName(path)
		if pkgAlias == "" {
			fmt.Fprintf(os.Stderr, "  [warn] 无法提取 package name: %s\n", path)
			return nil
		}

		relPath, _ := filepath.Rel(absRoot, filepath.Dir(path))
		importPath := filepath.ToSlash(filepath.Join(modulePath, relPath))

		src, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("读取文件失败 %s: %w", path, err)
		}

		matches := clientRe.FindAllStringSubmatch(string(src), -1)
		if len(matches) == 0 {
			return nil
		}

		for _, m := range matches {
			clientType := m[1]
			fieldName := strings.ToLower(clientType[:1]) + clientType[1:]

			nt, ok := pkgNodeMap[pkgAlias]
			if !ok {
				suffix := strings.TrimPrefix(pkgAlias, "pb_")
				if suffix == "" || suffix == pkgAlias {
					suffix = pkgAlias
				}
				nt = "Node" + strings.ToUpper(suffix[:1]) + suffix[1:] + "Service"
				fmt.Fprintf(os.Stderr, "  [warn] %q 不在 pkgNodeMap，猜测为 %s\n", pkgAlias, nt)
			}

			fmt.Printf("  [find] %s → %s.%s (%s)\n", clientType, pkgAlias, clientType, nt)
			clients = append(clients, ClientInfo{
				ClientType: clientType,
				FieldName:  fieldName,
				PkgAlias:   pkgAlias,
				ImportPath: importPath,
				NodeType:   nt,
			})
			importSet[importPath] = pkgAlias
		}
		return nil
	}); err != nil {
		die("遍历 pb 目录失败: %v", err)
	}

	if len(clients) == 0 {
		die("在 %s 中未找到任何 gRPC client", *pbDir)
	}
	fmt.Printf("\n共发现 %d 个 client\n", len(clients))

	var imports []ImportInfo
	for path, alias := range importSet {
		imports = append(imports, ImportInfo{Alias: alias, Path: path})
	}
	sort.Slice(imports, func(i, j int) bool { return imports[i].Path < imports[j].Path })

	tmpl := template.Must(template.New("gen").Parse(genTemplate))
	absOutput, _ := filepath.Abs(*output)
	if err := os.MkdirAll(filepath.Dir(absOutput), 0755); err != nil {
		die("创建输出目录失败: %v", err)
	}
	f, err := os.Create(absOutput)
	if err != nil {
		die("创建输出文件失败 %s: %v", *output, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, TemplateData{
		PackageName: *pkgName,
		Imports:     imports,
		Clients:     clients,
	}); err != nil {
		die("模板渲染失败: %v", err)
	}
	fmt.Printf("生成完成: %s\n", *output)
}

func readModulePath(root string) string {
	data, _ := os.ReadFile(filepath.Join(root, "go.mod"))
	re := regexp.MustCompile(`^module\s+(\S+)`)
	for _, line := range strings.Split(string(data), "\n") {
		if m := re.FindStringSubmatch(line); m != nil {
			return m[1]
		}
	}
	return ""
}

func extractPackageName(filePath string) string {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, filePath, nil, parser.PackageClauseOnly)
	if err != nil {
		return ""
	}
	return f.Name.Name
}

func die(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "错误: "+format+"\n", args...)
	os.Exit(1)
}

const genTemplate = `// Code generated by client-handler-gen; DO NOT EDIT.

package {{.PackageName}}

import (
	"io"
	"sync"

	"google.golang.org/grpc"

	etcdconn "server.slg.com/common/conns/etcdconn"
{{- range .Imports }}
	{{.Alias}} "{{.Path}}"
{{- end }}
)

// ClientHandler aggregates all generated gRPC clients.
// Each client is lazily initialized on first use via GetXxxClient().
// nil 表示连接失败，调用方自行判断。
type ClientHandler struct {
	mu      sync.Mutex
	conns   map[etcdconn.NodeService]*grpc.ClientConn
	closers []io.Closer

	// generated per-client fields
{{- range .Clients }}
	{{.FieldName}} {{.PkgAlias}}.{{.ClientType}}
{{- end }}
}

{{- range .Clients }}

// Get{{.ClientType}} returns the {{.PkgAlias}}.{{.ClientType}}, lazily connecting on first call.
func (ch *ClientHandler) Get{{.ClientType}}() {{.PkgAlias}}.{{.ClientType}} {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.{{.FieldName}} != nil {
		return ch.{{.FieldName}}
	}
	conn, err := ch.dialNodeLocked(etcdconn.{{.NodeType}})
	if err != nil {
		return nil
	}
	ch.{{.FieldName}} = {{.PkgAlias}}.New{{.ClientType}}(conn)
	return ch.{{.FieldName}}
}
{{- end }}
`
