// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: services/worldmap_server.proto

package pb_worldmap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorldMapNodeService_Stream_FullMethodName = "/pb_worldmap.WorldMapNodeService/Stream"
)

// WorldMapNodeServiceClient is the client API for WorldMapNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorldMapNodeServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket], error)
}

type worldMapNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldMapNodeServiceClient(cc grpc.ClientConnInterface) WorldMapNodeServiceClient {
	return &worldMapNodeServiceClient{cc}
}

func (c *worldMapNodeServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldMapNodeService_ServiceDesc.Streams[0], WorldMapNodeService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb_common.NodePacket, pb_common.NodePacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldMapNodeService_StreamClient = grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket]

// WorldMapNodeServiceServer is the server API for WorldMapNodeService service.
// All implementations must embed UnimplementedWorldMapNodeServiceServer
// for forward compatibility.
type WorldMapNodeServiceServer interface {
	Stream(grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]) error
	mustEmbedUnimplementedWorldMapNodeServiceServer()
}

// UnimplementedWorldMapNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldMapNodeServiceServer struct{}

func (UnimplementedWorldMapNodeServiceServer) Stream(grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedWorldMapNodeServiceServer) mustEmbedUnimplementedWorldMapNodeServiceServer() {}
func (UnimplementedWorldMapNodeServiceServer) testEmbeddedByValue()                             {}

// UnsafeWorldMapNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldMapNodeServiceServer will
// result in compilation errors.
type UnsafeWorldMapNodeServiceServer interface {
	mustEmbedUnimplementedWorldMapNodeServiceServer()
}

func RegisterWorldMapNodeServiceServer(s grpc.ServiceRegistrar, srv WorldMapNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorldMapNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorldMapNodeService_ServiceDesc, srv)
}

func _WorldMapNodeService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldMapNodeServiceServer).Stream(&grpc.GenericServerStream[pb_common.NodePacket, pb_common.NodePacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldMapNodeService_StreamServer = grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]

// WorldMapNodeService_ServiceDesc is the grpc.ServiceDesc for WorldMapNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldMapNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_worldmap.WorldMapNodeService",
	HandlerType: (*WorldMapNodeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _WorldMapNodeService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/worldmap_server.proto",
}
