// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: services/worldmap_server.proto

package pb_worldmap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorldMapService_Stream_FullMethodName = "/pb_worldmap.WorldMapService/Stream"
)

// WorldMapServiceClient is the client API for WorldMapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorldMapService 实时流 — game→worldmap 的玩家视野流
// 首条消息为握手（MsgID_WorldMapConnect），之后承载相机移动/地图下推
type WorldMapServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket], error)
}

type worldMapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldMapServiceClient(cc grpc.ClientConnInterface) WorldMapServiceClient {
	return &worldMapServiceClient{cc}
}

func (c *worldMapServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorldMapService_ServiceDesc.Streams[0], WorldMapService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb_common.NodePacket, pb_common.NodePacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldMapService_StreamClient = grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket]

// WorldMapServiceServer is the server API for WorldMapService service.
// All implementations must embed UnimplementedWorldMapServiceServer
// for forward compatibility.
//
// WorldMapService 实时流 — game→worldmap 的玩家视野流
// 首条消息为握手（MsgID_WorldMapConnect），之后承载相机移动/地图下推
type WorldMapServiceServer interface {
	Stream(grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]) error
	mustEmbedUnimplementedWorldMapServiceServer()
}

// UnimplementedWorldMapServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldMapServiceServer struct{}

func (UnimplementedWorldMapServiceServer) Stream(grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedWorldMapServiceServer) mustEmbedUnimplementedWorldMapServiceServer() {}
func (UnimplementedWorldMapServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorldMapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldMapServiceServer will
// result in compilation errors.
type UnsafeWorldMapServiceServer interface {
	mustEmbedUnimplementedWorldMapServiceServer()
}

func RegisterWorldMapServiceServer(s grpc.ServiceRegistrar, srv WorldMapServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorldMapServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorldMapService_ServiceDesc, srv)
}

func _WorldMapService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldMapServiceServer).Stream(&grpc.GenericServerStream[pb_common.NodePacket, pb_common.NodePacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorldMapService_StreamServer = grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]

// WorldMapService_ServiceDesc is the grpc.ServiceDesc for WorldMapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldMapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_worldmap.WorldMapService",
	HandlerType: (*WorldMapServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _WorldMapService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/worldmap_server.proto",
}

const (
	WorldMapHandler_CreateMarch_FullMethodName      = "/pb_worldmap.WorldMapHandler/CreateMarch"
	WorldMapHandler_CancelMarch_FullMethodName      = "/pb_worldmap.WorldMapHandler/CancelMarch"
	WorldMapHandler_MarchInfo_FullMethodName        = "/pb_worldmap.WorldMapHandler/MarchInfo"
	WorldMapHandler_MapData_FullMethodName          = "/pb_worldmap.WorldMapHandler/MapData"
	WorldMapHandler_CreateRole_FullMethodName       = "/pb_worldmap.WorldMapHandler/CreateRole"
	WorldMapHandler_SpawnReviewEvent_FullMethodName = "/pb_worldmap.WorldMapHandler/SpawnReviewEvent"
	WorldMapHandler_EventClick_FullMethodName       = "/pb_worldmap.WorldMapHandler/EventClick"
	WorldMapHandler_AbandonTile_FullMethodName      = "/pb_worldmap.WorldMapHandler/AbandonTile"
)

// WorldMapHandlerClient is the client API for WorldMapHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorldMapHandler 业务 RPC — game 通过 Unary 调用 worldmap
type WorldMapHandlerClient interface {
	// 行军
	CreateMarch(ctx context.Context, in *CreateMarchReq, opts ...grpc.CallOption) (*CreateMarchRsp, error)
	CancelMarch(ctx context.Context, in *CancelMarchReq, opts ...grpc.CallOption) (*CancelMarchRsp, error)
	MarchInfo(ctx context.Context, in *MarchInfoReq, opts ...grpc.CallOption) (*MarchInfoRsp, error)
	// 地图
	MapData(ctx context.Context, in *MapDataReq, opts ...grpc.CallOption) (*MapDataRsp, error)
	// 角色
	CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleRsp, error)
	// 审查：在主城 5×5 外圈刷出事件（扫荡行军可处理）
	SpawnReviewEvent(ctx context.Context, in *SpawnReviewEventReq, opts ...grpc.CallOption) (*SpawnReviewEventRsp, error)
	// 审查：气泡点击事件（采集/寻宝），+进度，超 100% 完成
	EventClick(ctx context.Context, in *EventClickReq, opts ...grpc.CallOption) (*EventClickRsp, error)
	// 地块：放弃已占领地块（释放归属，停止产出）
	AbandonTile(ctx context.Context, in *AbandonTileReq, opts ...grpc.CallOption) (*AbandonTileRsp, error)
}

type worldMapHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldMapHandlerClient(cc grpc.ClientConnInterface) WorldMapHandlerClient {
	return &worldMapHandlerClient{cc}
}

func (c *worldMapHandlerClient) CreateMarch(ctx context.Context, in *CreateMarchReq, opts ...grpc.CallOption) (*CreateMarchRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMarchRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_CreateMarch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldMapHandlerClient) CancelMarch(ctx context.Context, in *CancelMarchReq, opts ...grpc.CallOption) (*CancelMarchRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMarchRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_CancelMarch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldMapHandlerClient) MarchInfo(ctx context.Context, in *MarchInfoReq, opts ...grpc.CallOption) (*MarchInfoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarchInfoRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_MarchInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldMapHandlerClient) MapData(ctx context.Context, in *MapDataReq, opts ...grpc.CallOption) (*MapDataRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MapDataRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_MapData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldMapHandlerClient) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoleRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldMapHandlerClient) SpawnReviewEvent(ctx context.Context, in *SpawnReviewEventReq, opts ...grpc.CallOption) (*SpawnReviewEventRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpawnReviewEventRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_SpawnReviewEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldMapHandlerClient) EventClick(ctx context.Context, in *EventClickReq, opts ...grpc.CallOption) (*EventClickRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventClickRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_EventClick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldMapHandlerClient) AbandonTile(ctx context.Context, in *AbandonTileReq, opts ...grpc.CallOption) (*AbandonTileRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonTileRsp)
	err := c.cc.Invoke(ctx, WorldMapHandler_AbandonTile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorldMapHandlerServer is the server API for WorldMapHandler service.
// All implementations must embed UnimplementedWorldMapHandlerServer
// for forward compatibility.
//
// WorldMapHandler 业务 RPC — game 通过 Unary 调用 worldmap
type WorldMapHandlerServer interface {
	// 行军
	CreateMarch(context.Context, *CreateMarchReq) (*CreateMarchRsp, error)
	CancelMarch(context.Context, *CancelMarchReq) (*CancelMarchRsp, error)
	MarchInfo(context.Context, *MarchInfoReq) (*MarchInfoRsp, error)
	// 地图
	MapData(context.Context, *MapDataReq) (*MapDataRsp, error)
	// 角色
	CreateRole(context.Context, *CreateRoleReq) (*CreateRoleRsp, error)
	// 审查：在主城 5×5 外圈刷出事件（扫荡行军可处理）
	SpawnReviewEvent(context.Context, *SpawnReviewEventReq) (*SpawnReviewEventRsp, error)
	// 审查：气泡点击事件（采集/寻宝），+进度，超 100% 完成
	EventClick(context.Context, *EventClickReq) (*EventClickRsp, error)
	// 地块：放弃已占领地块（释放归属，停止产出）
	AbandonTile(context.Context, *AbandonTileReq) (*AbandonTileRsp, error)
	mustEmbedUnimplementedWorldMapHandlerServer()
}

// UnimplementedWorldMapHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorldMapHandlerServer struct{}

func (UnimplementedWorldMapHandlerServer) CreateMarch(context.Context, *CreateMarchReq) (*CreateMarchRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMarch not implemented")
}
func (UnimplementedWorldMapHandlerServer) CancelMarch(context.Context, *CancelMarchReq) (*CancelMarchRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMarch not implemented")
}
func (UnimplementedWorldMapHandlerServer) MarchInfo(context.Context, *MarchInfoReq) (*MarchInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarchInfo not implemented")
}
func (UnimplementedWorldMapHandlerServer) MapData(context.Context, *MapDataReq) (*MapDataRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MapData not implemented")
}
func (UnimplementedWorldMapHandlerServer) CreateRole(context.Context, *CreateRoleReq) (*CreateRoleRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedWorldMapHandlerServer) SpawnReviewEvent(context.Context, *SpawnReviewEventReq) (*SpawnReviewEventRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpawnReviewEvent not implemented")
}
func (UnimplementedWorldMapHandlerServer) EventClick(context.Context, *EventClickReq) (*EventClickRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EventClick not implemented")
}
func (UnimplementedWorldMapHandlerServer) AbandonTile(context.Context, *AbandonTileReq) (*AbandonTileRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonTile not implemented")
}
func (UnimplementedWorldMapHandlerServer) mustEmbedUnimplementedWorldMapHandlerServer() {}
func (UnimplementedWorldMapHandlerServer) testEmbeddedByValue()                         {}

// UnsafeWorldMapHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldMapHandlerServer will
// result in compilation errors.
type UnsafeWorldMapHandlerServer interface {
	mustEmbedUnimplementedWorldMapHandlerServer()
}

func RegisterWorldMapHandlerServer(s grpc.ServiceRegistrar, srv WorldMapHandlerServer) {
	// If the following call pancis, it indicates UnimplementedWorldMapHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorldMapHandler_ServiceDesc, srv)
}

func _WorldMapHandler_CreateMarch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).CreateMarch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_CreateMarch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).CreateMarch(ctx, req.(*CreateMarchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldMapHandler_CancelMarch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMarchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).CancelMarch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_CancelMarch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).CancelMarch(ctx, req.(*CancelMarchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldMapHandler_MarchInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarchInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).MarchInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_MarchInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).MarchInfo(ctx, req.(*MarchInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldMapHandler_MapData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MapDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).MapData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_MapData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).MapData(ctx, req.(*MapDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldMapHandler_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).CreateRole(ctx, req.(*CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldMapHandler_SpawnReviewEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnReviewEventReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).SpawnReviewEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_SpawnReviewEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).SpawnReviewEvent(ctx, req.(*SpawnReviewEventReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldMapHandler_EventClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventClickReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).EventClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_EventClick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).EventClick(ctx, req.(*EventClickReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorldMapHandler_AbandonTile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonTileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldMapHandlerServer).AbandonTile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorldMapHandler_AbandonTile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldMapHandlerServer).AbandonTile(ctx, req.(*AbandonTileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WorldMapHandler_ServiceDesc is the grpc.ServiceDesc for WorldMapHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldMapHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_worldmap.WorldMapHandler",
	HandlerType: (*WorldMapHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMarch",
			Handler:    _WorldMapHandler_CreateMarch_Handler,
		},
		{
			MethodName: "CancelMarch",
			Handler:    _WorldMapHandler_CancelMarch_Handler,
		},
		{
			MethodName: "MarchInfo",
			Handler:    _WorldMapHandler_MarchInfo_Handler,
		},
		{
			MethodName: "MapData",
			Handler:    _WorldMapHandler_MapData_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _WorldMapHandler_CreateRole_Handler,
		},
		{
			MethodName: "SpawnReviewEvent",
			Handler:    _WorldMapHandler_SpawnReviewEvent_Handler,
		},
		{
			MethodName: "EventClick",
			Handler:    _WorldMapHandler_EventClick_Handler,
		},
		{
			MethodName: "AbandonTile",
			Handler:    _WorldMapHandler_AbandonTile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/worldmap_server.proto",
}
