// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: services/worldmap_server.proto

package pb_worldmap

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorldMapService_Stream_FullMethodName = "/pb_worldmap.WorldMapService/Stream"
)

// WorldMapServiceClient is the client API for WorldMapService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorldMapServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (WorldMapService_StreamClient, error)
}

type worldMapServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldMapServiceClient(cc grpc.ClientConnInterface) WorldMapServiceClient {
	return &worldMapServiceClient{cc}
}

func (c *worldMapServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (WorldMapService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &WorldMapService_ServiceDesc.Streams[0], WorldMapService_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &worldMapServiceStreamClient{stream}
	return x, nil
}

type WorldMapService_StreamClient interface {
	Send(*pb_common.NodePacket) error
	Recv() (*pb_common.NodePacket, error)
	grpc.ClientStream
}

type worldMapServiceStreamClient struct {
	grpc.ClientStream
}

func (x *worldMapServiceStreamClient) Send(m *pb_common.NodePacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *worldMapServiceStreamClient) Recv() (*pb_common.NodePacket, error) {
	m := new(pb_common.NodePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorldMapServiceServer is the server API for WorldMapService service.
// All implementations must embed UnimplementedWorldMapServiceServer
// for forward compatibility
type WorldMapServiceServer interface {
	Stream(WorldMapService_StreamServer) error
	mustEmbedUnimplementedWorldMapServiceServer()
}

// UnimplementedWorldMapServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorldMapServiceServer struct {
}

func (UnimplementedWorldMapServiceServer) Stream(WorldMapService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedWorldMapServiceServer) mustEmbedUnimplementedWorldMapServiceServer() {}

// UnsafeWorldMapServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldMapServiceServer will
// result in compilation errors.
type UnsafeWorldMapServiceServer interface {
	mustEmbedUnimplementedWorldMapServiceServer()
}

func RegisterWorldMapServiceServer(s grpc.ServiceRegistrar, srv WorldMapServiceServer) {
	s.RegisterService(&WorldMapService_ServiceDesc, srv)
}

func _WorldMapService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldMapServiceServer).Stream(&worldMapServiceStreamServer{stream})
}

type WorldMapService_StreamServer interface {
	Send(*pb_common.NodePacket) error
	Recv() (*pb_common.NodePacket, error)
	grpc.ServerStream
}

type worldMapServiceStreamServer struct {
	grpc.ServerStream
}

func (x *worldMapServiceStreamServer) Send(m *pb_common.NodePacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *worldMapServiceStreamServer) Recv() (*pb_common.NodePacket, error) {
	m := new(pb_common.NodePacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorldMapService_ServiceDesc is the grpc.ServiceDesc for WorldMapService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldMapService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_worldmap.WorldMapService",
	HandlerType: (*WorldMapServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _WorldMapService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/worldmap_server.proto",
}

const ()

// WorldMapHandlerClient is the client API for WorldMapHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorldMapHandlerClient interface {
}

type worldMapHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorldMapHandlerClient(cc grpc.ClientConnInterface) WorldMapHandlerClient {
	return &worldMapHandlerClient{cc}
}

// WorldMapHandlerServer is the server API for WorldMapHandler service.
// All implementations must embed UnimplementedWorldMapHandlerServer
// for forward compatibility
type WorldMapHandlerServer interface {
	mustEmbedUnimplementedWorldMapHandlerServer()
}

// UnimplementedWorldMapHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedWorldMapHandlerServer struct {
}

func (UnimplementedWorldMapHandlerServer) mustEmbedUnimplementedWorldMapHandlerServer() {}

// UnsafeWorldMapHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorldMapHandlerServer will
// result in compilation errors.
type UnsafeWorldMapHandlerServer interface {
	mustEmbedUnimplementedWorldMapHandlerServer()
}

func RegisterWorldMapHandlerServer(s grpc.ServiceRegistrar, srv WorldMapHandlerServer) {
	s.RegisterService(&WorldMapHandler_ServiceDesc, srv)
}

// WorldMapHandler_ServiceDesc is the grpc.ServiceDesc for WorldMapHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorldMapHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_worldmap.WorldMapHandler",
	HandlerType: (*WorldMapHandlerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "services/worldmap_server.proto",
}
