// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: redis_stream.proto

package pb_redis_stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MarchEventType 行军事件类型
type MarchEventType int32

const (
	MarchEventType_MARCH_EVENT_UNKNOWN     MarchEventType = 0
	MarchEventType_MARCH_EVENT_ARRIVED     MarchEventType = 1 // 行军到达（目标点结算，如占领/采集/驻守）
	MarchEventType_MARCH_EVENT_CANCELED    MarchEventType = 2 // 行军取消
	MarchEventType_MARCH_EVENT_BACKARRIVED MarchEventType = 3 // 行军回城到站
)

// Enum value maps for MarchEventType.
var (
	MarchEventType_name = map[int32]string{
		0: "MARCH_EVENT_UNKNOWN",
		1: "MARCH_EVENT_ARRIVED",
		2: "MARCH_EVENT_CANCELED",
		3: "MARCH_EVENT_BACKARRIVED",
	}
	MarchEventType_value = map[string]int32{
		"MARCH_EVENT_UNKNOWN":     0,
		"MARCH_EVENT_ARRIVED":     1,
		"MARCH_EVENT_CANCELED":    2,
		"MARCH_EVENT_BACKARRIVED": 3,
	}
)

func (x MarchEventType) Enum() *MarchEventType {
	p := new(MarchEventType)
	*p = x
	return p
}

func (x MarchEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarchEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_redis_stream_proto_enumTypes[0].Descriptor()
}

func (MarchEventType) Type() protoreflect.EnumType {
	return &file_redis_stream_proto_enumTypes[0]
}

func (x MarchEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarchEventType.Descriptor instead.
func (MarchEventType) EnumDescriptor() ([]byte, []int) {
	return file_redis_stream_proto_rawDescGZIP(), []int{0}
}

// MarchEvent 行军事件 — worldmap → game，经由 Redis Stream 投递
type MarchEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         MarchEventType     `protobuf:"varint,1,opt,name=type,proto3,enum=redis_stream.MarchEventType" json:"type,omitempty"`
	MarchId      uint64             `protobuf:"varint,2,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	RoleId       uint64             `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	ToMapId      int32              `protobuf:"varint,4,opt,name=to_map_id,json=toMapId,proto3" json:"to_map_id,omitempty"`             // 仅 ARRIVED 有效
	MarchType    int32              `protobuf:"varint,5,opt,name=march_type,json=marchType,proto3" json:"march_type,omitempty"`         // 仅 ARRIVED 有效
	Ts           int64              `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`                                        // unix 时间戳
	State        int32              `protobuf:"varint,7,opt,name=state,proto3" json:"state,omitempty"`                                  // 结算后行军状态 (pb_maps_march.MarchState): 驻留=6, 回城=5
	BattleResult *MarchBattleResult `protobuf:"bytes,8,opt,name=battle_result,json=battleResult,proto3" json:"battle_result,omitempty"` // 战斗结果（仅攻击行军 ARRIVED 携带）
}

func (x *MarchEvent) Reset() {
	*x = MarchEvent{}
	mi := &file_redis_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchEvent) ProtoMessage() {}

func (x *MarchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_redis_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchEvent.ProtoReflect.Descriptor instead.
func (*MarchEvent) Descriptor() ([]byte, []int) {
	return file_redis_stream_proto_rawDescGZIP(), []int{0}
}

func (x *MarchEvent) GetType() MarchEventType {
	if x != nil {
		return x.Type
	}
	return MarchEventType_MARCH_EVENT_UNKNOWN
}

func (x *MarchEvent) GetMarchId() uint64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *MarchEvent) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *MarchEvent) GetToMapId() int32 {
	if x != nil {
		return x.ToMapId
	}
	return 0
}

func (x *MarchEvent) GetMarchType() int32 {
	if x != nil {
		return x.MarchType
	}
	return 0
}

func (x *MarchEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *MarchEvent) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *MarchEvent) GetBattleResult() *MarchBattleResult {
	if x != nil {
		return x.BattleResult
	}
	return nil
}

// MarchBattleResult 战斗结果（worldmap → game，供经验发放）
type MarchBattleResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttackerWin bool           `protobuf:"varint,1,opt,name=attacker_win,json=attackerWin,proto3" json:"attacker_win,omitempty"` // 攻击方是否获胜
	HeroExp     []*HeroExpItem `protobuf:"bytes,2,rep,name=hero_exp,json=heroExp,proto3" json:"hero_exp,omitempty"`              // 参战英雄总经验
}

func (x *MarchBattleResult) Reset() {
	*x = MarchBattleResult{}
	mi := &file_redis_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchBattleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchBattleResult) ProtoMessage() {}

func (x *MarchBattleResult) ProtoReflect() protoreflect.Message {
	mi := &file_redis_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchBattleResult.ProtoReflect.Descriptor instead.
func (*MarchBattleResult) Descriptor() ([]byte, []int) {
	return file_redis_stream_proto_rawDescGZIP(), []int{1}
}

func (x *MarchBattleResult) GetAttackerWin() bool {
	if x != nil {
		return x.AttackerWin
	}
	return false
}

func (x *MarchBattleResult) GetHeroExp() []*HeroExpItem {
	if x != nil {
		return x.HeroExp
	}
	return nil
}

// HeroExpItem 参战英雄经验
type HeroExpItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"` // 英雄实例ID
	Exp    uint32 `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`                     // 本次获得总经验
}

func (x *HeroExpItem) Reset() {
	*x = HeroExpItem{}
	mi := &file_redis_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroExpItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroExpItem) ProtoMessage() {}

func (x *HeroExpItem) ProtoReflect() protoreflect.Message {
	mi := &file_redis_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroExpItem.ProtoReflect.Descriptor instead.
func (*HeroExpItem) Descriptor() ([]byte, []int) {
	return file_redis_stream_proto_rawDescGZIP(), []int{2}
}

func (x *HeroExpItem) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroExpItem) GetExp() uint32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

// RoleEnterEvent 角色进服事件 — login EnterServer 成功后发布，所有 gateway 订阅。
// 本机持有该角色旧连接则踢掉（跨 gateway 异设备登录 / 同 gateway 重连双开）。
type RoleEnterEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId        uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`                       // 进服角色
	ServerId      uint32 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`                 // 进入的区服
	GatewayNodeId string `protobuf:"bytes,3,opt,name=gateway_node_id,json=gatewayNodeId,proto3" json:"gateway_node_id,omitempty"` // 角色所在 gateway 节点标识（login 记录/广播）
}

func (x *RoleEnterEvent) Reset() {
	*x = RoleEnterEvent{}
	mi := &file_redis_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleEnterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleEnterEvent) ProtoMessage() {}

func (x *RoleEnterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_redis_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleEnterEvent.ProtoReflect.Descriptor instead.
func (*RoleEnterEvent) Descriptor() ([]byte, []int) {
	return file_redis_stream_proto_rawDescGZIP(), []int{3}
}

func (x *RoleEnterEvent) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleEnterEvent) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *RoleEnterEvent) GetGatewayNodeId() string {
	if x != nil {
		return x.GatewayNodeId
	}
	return ""
}

// StreamEnvelope 统一的消息信封
type StreamEnvelope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic     string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`          // 主题名，如 "march"
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`      // 业务消息序列化后的 bytes
	Timestamp int64  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 发布时间戳
}

func (x *StreamEnvelope) Reset() {
	*x = StreamEnvelope{}
	mi := &file_redis_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnvelope) ProtoMessage() {}

func (x *StreamEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_redis_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnvelope.ProtoReflect.Descriptor instead.
func (*StreamEnvelope) Descriptor() ([]byte, []int) {
	return file_redis_stream_proto_rawDescGZIP(), []int{4}
}

func (x *StreamEnvelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StreamEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_redis_stream_proto protoreflect.FileDescriptor

var file_redis_stream_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x22, 0x99, 0x02, 0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x30, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1c, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d,
	0x61, 0x72, 0x63, 0x68, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x09, 0x74, 0x6f, 0x5f, 0x6d, 0x61,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x6f, 0x4d, 0x61,
	0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x74, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x62, 0x61, 0x74, 0x74,
	0x6c, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1f, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4d,
	0x61, 0x72, 0x63, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x0c, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6c,
	0x0a, 0x11, 0x4d, 0x61, 0x72, 0x63, 0x68, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x5f,
	0x77, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x57, 0x69, 0x6e, 0x12, 0x34, 0x0a, 0x08, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x65,
	0x78, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65, 0x64, 0x69, 0x73,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x78, 0x70, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x45, 0x78, 0x70, 0x22, 0x38, 0x0a, 0x0b,
	0x48, 0x65, 0x72, 0x6f, 0x45, 0x78, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x68,
	0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65,
	0x72, 0x6f, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x6e, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x79, 0x0a, 0x0e, 0x4d, 0x61, 0x72, 0x63, 0x68, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x52, 0x43,
	0x48, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54,
	0x5f, 0x41, 0x52, 0x52, 0x49, 0x56, 0x45, 0x44, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x41,
	0x52, 0x43, 0x48, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c,
	0x45, 0x44, 0x10, 0x02, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x41, 0x52, 0x52, 0x49, 0x56, 0x45, 0x44, 0x10,
	0x03, 0x42, 0x30, 0x5a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x5f, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redis_stream_proto_rawDescOnce sync.Once
	file_redis_stream_proto_rawDescData = file_redis_stream_proto_rawDesc
)

func file_redis_stream_proto_rawDescGZIP() []byte {
	file_redis_stream_proto_rawDescOnce.Do(func() {
		file_redis_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_redis_stream_proto_rawDescData)
	})
	return file_redis_stream_proto_rawDescData
}

var file_redis_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_redis_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_redis_stream_proto_goTypes = []any{
	(MarchEventType)(0),       // 0: redis_stream.MarchEventType
	(*MarchEvent)(nil),        // 1: redis_stream.MarchEvent
	(*MarchBattleResult)(nil), // 2: redis_stream.MarchBattleResult
	(*HeroExpItem)(nil),       // 3: redis_stream.HeroExpItem
	(*RoleEnterEvent)(nil),    // 4: redis_stream.RoleEnterEvent
	(*StreamEnvelope)(nil),    // 5: redis_stream.StreamEnvelope
}
var file_redis_stream_proto_depIdxs = []int32{
	0, // 0: redis_stream.MarchEvent.type:type_name -> redis_stream.MarchEventType
	2, // 1: redis_stream.MarchEvent.battle_result:type_name -> redis_stream.MarchBattleResult
	3, // 2: redis_stream.MarchBattleResult.hero_exp:type_name -> redis_stream.HeroExpItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_redis_stream_proto_init() }
func file_redis_stream_proto_init() {
	if File_redis_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redis_stream_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_stream_proto_goTypes,
		DependencyIndexes: file_redis_stream_proto_depIdxs,
		EnumInfos:         file_redis_stream_proto_enumTypes,
		MessageInfos:      file_redis_stream_proto_msgTypes,
	}.Build()
	File_redis_stream_proto = out.File
	file_redis_stream_proto_rawDesc = nil
	file_redis_stream_proto_goTypes = nil
	file_redis_stream_proto_depIdxs = nil
}
