// Code generated by client-worldmap_handlers-gen; DO NOT EDIT.

package rpc_handlers

import (
	"io"
	"sync"

	"google.golang.org/grpc"

	pb_game "server.slg.com/api/protocol/pb/pb_game"
	pb_gateway "server.slg.com/api/protocol/pb/pb_gateway"
	pb_worldmap "server.slg.com/api/protocol/pb/pb_worldmap"
	"server.slg.com/common/common_declarations"
)

// ClientHandler aggregates all generated gRPC clients.
// Each client is lazily initialized on first use via GetXxxClient().
// nil 表示连接失败，调用方自行判断。
type ClientHandler struct {
	mu                    sync.Mutex
	instance              string
	conns                 map[common_declarations.NodeService]*grpc.ClientConn
	closers               []io.Closer
	dialOptions           []grpc.DialOption
	gameServiceClient     pb_game.GameServiceClient
	gameHandlerClient     pb_game.GameHandlerClient
	gatewayServiceClient  pb_gateway.GatewayServiceClient
	gatewayHandlerClient  pb_gateway.GatewayHandlerClient
	worldMapServiceClient pb_worldmap.WorldMapServiceClient
	worldMapHandlerClient pb_worldmap.WorldMapHandlerClient
}

// NewClientHandler creates a ClientHandler bound to the given instance.
// 所有节点发现均按 nodeType + instance 精确定位（单例配对场景）。
func NewClientHandler(instance string, dialOptions ...grpc.DialOption) *ClientHandler {
	return &ClientHandler{
		instance:    instance,
		conns:       make(map[common_declarations.NodeService]*grpc.ClientConn),
		dialOptions: dialOptions,
	}
}

// GetGameServiceClient returns the pb_game.GameServiceClient, lazily connecting on first call.
// 拨号使用内置默认超时。
func (ch *ClientHandler) GetGameServiceClient() pb_game.GameServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gameServiceClient != nil {
		return ch.gameServiceClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGameService, false)
	if err != nil {
		return nil
	}
	ch.gameServiceClient = pb_game.NewGameServiceClient(conn)
	return ch.gameServiceClient
}

// GetGameServiceClientWait returns the pb_game.GameServiceClient, waiting indefinitely for the connection on first call.
// 拨号阻塞等待就绪（无超时），适用于启动期依赖对方节点就绪的场景。
func (ch *ClientHandler) GetGameServiceClientWait() pb_game.GameServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gameServiceClient != nil {
		return ch.gameServiceClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGameService, true)
	if err != nil {
		return nil
	}
	ch.gameServiceClient = pb_game.NewGameServiceClient(conn)
	return ch.gameServiceClient
}

// GetGameHandlerClient returns the pb_game.GameHandlerClient, lazily connecting on first call.
// 拨号使用内置默认超时。
func (ch *ClientHandler) GetGameHandlerClient() pb_game.GameHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gameHandlerClient != nil {
		return ch.gameHandlerClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGameService, false)
	if err != nil {
		return nil
	}
	ch.gameHandlerClient = pb_game.NewGameHandlerClient(conn)
	return ch.gameHandlerClient
}

// GetGameHandlerClientWait returns the pb_game.GameHandlerClient, waiting indefinitely for the connection on first call.
// 拨号阻塞等待就绪（无超时），适用于启动期依赖对方节点就绪的场景。
func (ch *ClientHandler) GetGameHandlerClientWait() pb_game.GameHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gameHandlerClient != nil {
		return ch.gameHandlerClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGameService, true)
	if err != nil {
		return nil
	}
	ch.gameHandlerClient = pb_game.NewGameHandlerClient(conn)
	return ch.gameHandlerClient
}

// GetGatewayServiceClient returns the pb_gateway.GatewayServiceClient, lazily connecting on first call.
// 拨号使用内置默认超时。
func (ch *ClientHandler) GetGatewayServiceClient() pb_gateway.GatewayServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gatewayServiceClient != nil {
		return ch.gatewayServiceClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGatewayService, false)
	if err != nil {
		return nil
	}
	ch.gatewayServiceClient = pb_gateway.NewGatewayServiceClient(conn)
	return ch.gatewayServiceClient
}

// GetGatewayServiceClientWait returns the pb_gateway.GatewayServiceClient, waiting indefinitely for the connection on first call.
// 拨号阻塞等待就绪（无超时），适用于启动期依赖对方节点就绪的场景。
func (ch *ClientHandler) GetGatewayServiceClientWait() pb_gateway.GatewayServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gatewayServiceClient != nil {
		return ch.gatewayServiceClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGatewayService, true)
	if err != nil {
		return nil
	}
	ch.gatewayServiceClient = pb_gateway.NewGatewayServiceClient(conn)
	return ch.gatewayServiceClient
}

// GetGatewayHandlerClient returns the pb_gateway.GatewayHandlerClient, lazily connecting on first call.
// 拨号使用内置默认超时。
func (ch *ClientHandler) GetGatewayHandlerClient() pb_gateway.GatewayHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gatewayHandlerClient != nil {
		return ch.gatewayHandlerClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGatewayService, false)
	if err != nil {
		return nil
	}
	ch.gatewayHandlerClient = pb_gateway.NewGatewayHandlerClient(conn)
	return ch.gatewayHandlerClient
}

// GetGatewayHandlerClientWait returns the pb_gateway.GatewayHandlerClient, waiting indefinitely for the connection on first call.
// 拨号阻塞等待就绪（无超时），适用于启动期依赖对方节点就绪的场景。
func (ch *ClientHandler) GetGatewayHandlerClientWait() pb_gateway.GatewayHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gatewayHandlerClient != nil {
		return ch.gatewayHandlerClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeGatewayService, true)
	if err != nil {
		return nil
	}
	ch.gatewayHandlerClient = pb_gateway.NewGatewayHandlerClient(conn)
	return ch.gatewayHandlerClient
}

// GetWorldMapServiceClient returns the pb_worldmap.WorldMapServiceClient, lazily connecting on first call.
// 拨号使用内置默认超时。
func (ch *ClientHandler) GetWorldMapServiceClient() pb_worldmap.WorldMapServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.worldMapServiceClient != nil {
		return ch.worldMapServiceClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeWorldMapService, false)
	if err != nil {
		return nil
	}
	ch.worldMapServiceClient = pb_worldmap.NewWorldMapServiceClient(conn)
	return ch.worldMapServiceClient
}

// GetWorldMapServiceClientWait returns the pb_worldmap.WorldMapServiceClient, waiting indefinitely for the connection on first call.
// 拨号阻塞等待就绪（无超时），适用于启动期依赖对方节点就绪的场景。
func (ch *ClientHandler) GetWorldMapServiceClientWait() pb_worldmap.WorldMapServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.worldMapServiceClient != nil {
		return ch.worldMapServiceClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeWorldMapService, true)
	if err != nil {
		return nil
	}
	ch.worldMapServiceClient = pb_worldmap.NewWorldMapServiceClient(conn)
	return ch.worldMapServiceClient
}

// GetWorldMapHandlerClient returns the pb_worldmap.WorldMapHandlerClient, lazily connecting on first call.
// 拨号使用内置默认超时。
func (ch *ClientHandler) GetWorldMapHandlerClient() pb_worldmap.WorldMapHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.worldMapHandlerClient != nil {
		return ch.worldMapHandlerClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeWorldMapService, false)
	if err != nil {
		return nil
	}
	ch.worldMapHandlerClient = pb_worldmap.NewWorldMapHandlerClient(conn)
	return ch.worldMapHandlerClient
}

// GetWorldMapHandlerClientWait returns the pb_worldmap.WorldMapHandlerClient, waiting indefinitely for the connection on first call.
// 拨号阻塞等待就绪（无超时），适用于启动期依赖对方节点就绪的场景。
func (ch *ClientHandler) GetWorldMapHandlerClientWait() pb_worldmap.WorldMapHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.worldMapHandlerClient != nil {
		return ch.worldMapHandlerClient
	}
	conn, err := ch.dialNodeLocked(common_declarations.NodeWorldMapService, true)
	if err != nil {
		return nil
	}
	ch.worldMapHandlerClient = pb_worldmap.NewWorldMapHandlerClient(conn)
	return ch.worldMapHandlerClient
}
