// Code generated by client-handler-gen; DO NOT EDIT.

package rpc_handlers

import (
	"io"
	"sync"

	"google.golang.org/grpc"

	pb_game "server.slg.com/api/protocol/pb/pb_game"
	pb_gateway "server.slg.com/api/protocol/pb/pb_gateway"
	pb_worldmap "server.slg.com/api/protocol/pb/pb_worldmap"
	etcdconn "server.slg.com/common/conns/etcdconn"
)

// ClientHandler aggregates all generated gRPC clients.
// Each client is lazily initialized on first use via GetXxxClient().
// nil 表示连接失败，调用方自行判断。
type ClientHandler struct {
	mu      sync.Mutex
	conns   map[etcdconn.NodeService]*grpc.ClientConn
	closers []io.Closer

	// generated per-client fields
	gameServiceClient pb_game.GameServiceClient
	gameHandlerClient pb_game.GameHandlerClient
	gatewayServiceClient pb_gateway.GatewayServiceClient
	gatewayHandlerClient pb_gateway.GatewayHandlerClient
	worldMapServiceClient pb_worldmap.WorldMapServiceClient
	worldMapHandlerClient pb_worldmap.WorldMapHandlerClient
}

// GetGameServiceClient returns the pb_game.GameServiceClient, lazily connecting on first call.
func (ch *ClientHandler) GetGameServiceClient() pb_game.GameServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gameServiceClient != nil {
		return ch.gameServiceClient
	}
	conn, err := ch.dialNodeLocked(etcdconn.NodeGameService)
	if err != nil {
		return nil
	}
	ch.gameServiceClient = pb_game.NewGameServiceClient(conn)
	return ch.gameServiceClient
}

// GetGameHandlerClient returns the pb_game.GameHandlerClient, lazily connecting on first call.
func (ch *ClientHandler) GetGameHandlerClient() pb_game.GameHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gameHandlerClient != nil {
		return ch.gameHandlerClient
	}
	conn, err := ch.dialNodeLocked(etcdconn.NodeGameService)
	if err != nil {
		return nil
	}
	ch.gameHandlerClient = pb_game.NewGameHandlerClient(conn)
	return ch.gameHandlerClient
}

// GetGatewayServiceClient returns the pb_gateway.GatewayServiceClient, lazily connecting on first call.
func (ch *ClientHandler) GetGatewayServiceClient() pb_gateway.GatewayServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gatewayServiceClient != nil {
		return ch.gatewayServiceClient
	}
	conn, err := ch.dialNodeLocked(etcdconn.NodeGatewayService)
	if err != nil {
		return nil
	}
	ch.gatewayServiceClient = pb_gateway.NewGatewayServiceClient(conn)
	return ch.gatewayServiceClient
}

// GetGatewayHandlerClient returns the pb_gateway.GatewayHandlerClient, lazily connecting on first call.
func (ch *ClientHandler) GetGatewayHandlerClient() pb_gateway.GatewayHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.gatewayHandlerClient != nil {
		return ch.gatewayHandlerClient
	}
	conn, err := ch.dialNodeLocked(etcdconn.NodeGatewayService)
	if err != nil {
		return nil
	}
	ch.gatewayHandlerClient = pb_gateway.NewGatewayHandlerClient(conn)
	return ch.gatewayHandlerClient
}

// GetWorldMapServiceClient returns the pb_worldmap.WorldMapServiceClient, lazily connecting on first call.
func (ch *ClientHandler) GetWorldMapServiceClient() pb_worldmap.WorldMapServiceClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.worldMapServiceClient != nil {
		return ch.worldMapServiceClient
	}
	conn, err := ch.dialNodeLocked(etcdconn.NodeWorldMapService)
	if err != nil {
		return nil
	}
	ch.worldMapServiceClient = pb_worldmap.NewWorldMapServiceClient(conn)
	return ch.worldMapServiceClient
}

// GetWorldMapHandlerClient returns the pb_worldmap.WorldMapHandlerClient, lazily connecting on first call.
func (ch *ClientHandler) GetWorldMapHandlerClient() pb_worldmap.WorldMapHandlerClient {
	ch.mu.Lock()
	defer ch.mu.Unlock()
	if ch.worldMapHandlerClient != nil {
		return ch.worldMapHandlerClient
	}
	conn, err := ch.dialNodeLocked(etcdconn.NodeWorldMapService)
	if err != nil {
		return nil
	}
	ch.worldMapHandlerClient = pb_worldmap.NewWorldMapHandlerClient(conn)
	return ch.worldMapHandlerClient
}
