// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: services/game_server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameNodeService_Stream_FullMethodName     = "/game.GameNodeService/Stream"
	GameNodeService_CreateRole_FullMethodName = "/game.GameNodeService/CreateRole"
	GameNodeService_LoginOnce_FullMethodName  = "/game.GameNodeService/LoginOnce"
)

// GameNodeServiceClient is the client API for GameNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameNodeServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (GameNodeService_StreamClient, error)
	// 登录服创建玩家
	CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleRsp, error)
	LoginOnce(ctx context.Context, in *LoginOnceReq, opts ...grpc.CallOption) (*LoginOnceRsp, error)
}

type gameNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameNodeServiceClient(cc grpc.ClientConnInterface) GameNodeServiceClient {
	return &gameNodeServiceClient{cc}
}

func (c *gameNodeServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (GameNodeService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameNodeService_ServiceDesc.Streams[0], GameNodeService_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gameNodeServiceStreamClient{stream}
	return x, nil
}

type GameNodeService_StreamClient interface {
	Send(*NodePacket) error
	Recv() (*NodePacket, error)
	grpc.ClientStream
}

type gameNodeServiceStreamClient struct {
	grpc.ClientStream
}

func (x *gameNodeServiceStreamClient) Send(m *NodePacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameNodeServiceStreamClient) Recv() (*NodePacket, error) {
	m := new(NodePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameNodeServiceClient) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleRsp, error) {
	out := new(CreateRoleRsp)
	err := c.cc.Invoke(ctx, GameNodeService_CreateRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameNodeServiceClient) LoginOnce(ctx context.Context, in *LoginOnceReq, opts ...grpc.CallOption) (*LoginOnceRsp, error) {
	out := new(LoginOnceRsp)
	err := c.cc.Invoke(ctx, GameNodeService_LoginOnce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameNodeServiceServer is the server API for GameNodeService service.
// All implementations must embed UnimplementedGameNodeServiceServer
// for forward compatibility
type GameNodeServiceServer interface {
	Stream(GameNodeService_StreamServer) error
	// 登录服创建玩家
	CreateRole(context.Context, *CreateRoleReq) (*CreateRoleRsp, error)
	LoginOnce(context.Context, *LoginOnceReq) (*LoginOnceRsp, error)
	mustEmbedUnimplementedGameNodeServiceServer()
}

// UnimplementedGameNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameNodeServiceServer struct {
}

func (UnimplementedGameNodeServiceServer) Stream(GameNodeService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGameNodeServiceServer) CreateRole(context.Context, *CreateRoleReq) (*CreateRoleRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedGameNodeServiceServer) LoginOnce(context.Context, *LoginOnceReq) (*LoginOnceRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOnce not implemented")
}
func (UnimplementedGameNodeServiceServer) mustEmbedUnimplementedGameNodeServiceServer() {}

// UnsafeGameNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameNodeServiceServer will
// result in compilation errors.
type UnsafeGameNodeServiceServer interface {
	mustEmbedUnimplementedGameNodeServiceServer()
}

func RegisterGameNodeServiceServer(s grpc.ServiceRegistrar, srv GameNodeServiceServer) {
	s.RegisterService(&GameNodeService_ServiceDesc, srv)
}

func _GameNodeService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameNodeServiceServer).Stream(&gameNodeServiceStreamServer{stream})
}

type GameNodeService_StreamServer interface {
	Send(*NodePacket) error
	Recv() (*NodePacket, error)
	grpc.ServerStream
}

type gameNodeServiceStreamServer struct {
	grpc.ServerStream
}

func (x *gameNodeServiceStreamServer) Send(m *NodePacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameNodeServiceStreamServer) Recv() (*NodePacket, error) {
	m := new(NodePacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GameNodeService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).CreateRole(ctx, req.(*CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameNodeService_LoginOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginOnceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).LoginOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_LoginOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).LoginOnce(ctx, req.(*LoginOnceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameNodeService_ServiceDesc is the grpc.ServiceDesc for GameNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GameNodeService",
	HandlerType: (*GameNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _GameNodeService_CreateRole_Handler,
		},
		{
			MethodName: "LoginOnce",
			Handler:    _GameNodeService_LoginOnce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GameNodeService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/game_server.proto",
}

const (
	GatewayNodeService_NotifyInfo_FullMethodName = "/game.GatewayNodeService/NotifyInfo"
)

// GatewayNodeServiceClient is the client API for GatewayNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayNodeServiceClient interface {
	// 登录服创建玩家
	NotifyInfo(ctx context.Context, in *NotifyInfoReq, opts ...grpc.CallOption) (*NotifyInfoRsp, error)
}

type gatewayNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayNodeServiceClient(cc grpc.ClientConnInterface) GatewayNodeServiceClient {
	return &gatewayNodeServiceClient{cc}
}

func (c *gatewayNodeServiceClient) NotifyInfo(ctx context.Context, in *NotifyInfoReq, opts ...grpc.CallOption) (*NotifyInfoRsp, error) {
	out := new(NotifyInfoRsp)
	err := c.cc.Invoke(ctx, GatewayNodeService_NotifyInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayNodeServiceServer is the server API for GatewayNodeService service.
// All implementations must embed UnimplementedGatewayNodeServiceServer
// for forward compatibility
type GatewayNodeServiceServer interface {
	// 登录服创建玩家
	NotifyInfo(context.Context, *NotifyInfoReq) (*NotifyInfoRsp, error)
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

// UnimplementedGatewayNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayNodeServiceServer struct {
}

func (UnimplementedGatewayNodeServiceServer) NotifyInfo(context.Context, *NotifyInfoReq) (*NotifyInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyInfo not implemented")
}
func (UnimplementedGatewayNodeServiceServer) mustEmbedUnimplementedGatewayNodeServiceServer() {}

// UnsafeGatewayNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayNodeServiceServer will
// result in compilation errors.
type UnsafeGatewayNodeServiceServer interface {
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

func RegisterGatewayNodeServiceServer(s grpc.ServiceRegistrar, srv GatewayNodeServiceServer) {
	s.RegisterService(&GatewayNodeService_ServiceDesc, srv)
}

func _GatewayNodeService_NotifyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNodeServiceServer).NotifyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNodeService_NotifyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNodeServiceServer).NotifyInfo(ctx, req.(*NotifyInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayNodeService_ServiceDesc is the grpc.ServiceDesc for GatewayNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.GatewayNodeService",
	HandlerType: (*GatewayNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyInfo",
			Handler:    _GatewayNodeService_NotifyInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/game_server.proto",
}
