// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: services/game_server.proto

package pb_game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GameService_Stream_FullMethodName = "/pb_game.GameService/Stream"
)

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (GameService_StreamClient, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (GameService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[0], GameService_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceStreamClient{stream}
	return x, nil
}

type GameService_StreamClient interface {
	Send(*pb_common.NodePacket) error
	Recv() (*pb_common.NodePacket, error)
	grpc.ClientStream
}

type gameServiceStreamClient struct {
	grpc.ClientStream
}

func (x *gameServiceStreamClient) Send(m *pb_common.NodePacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServiceStreamClient) Recv() (*pb_common.NodePacket, error) {
	m := new(pb_common.NodePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	Stream(GameService_StreamServer) error
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) Stream(GameService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).Stream(&gameServiceStreamServer{stream})
}

type GameService_StreamServer interface {
	Send(*pb_common.NodePacket) error
	Recv() (*pb_common.NodePacket, error)
	grpc.ServerStream
}

type gameServiceStreamServer struct {
	grpc.ServerStream
}

func (x *gameServiceStreamServer) Send(m *pb_common.NodePacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServiceStreamServer) Recv() (*pb_common.NodePacket, error) {
	m := new(pb_common.NodePacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GameService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/game_server.proto",
}

const (
	GameHandler_CreateRole_FullMethodName = "/pb_game.GameHandler/CreateRole"
	GameHandler_LoginOnce_FullMethodName  = "/pb_game.GameHandler/LoginOnce"
)

// GameHandlerClient is the client API for GameHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameHandlerClient interface {
	// 登录服创建玩家
	CreateRole(ctx context.Context, in *pb_common.CreateRoleReq, opts ...grpc.CallOption) (*pb_common.CreateRoleRsp, error)
	LoginOnce(ctx context.Context, in *pb_common.LoginOnceReq, opts ...grpc.CallOption) (*pb_common.LoginOnceRsp, error)
}

type gameHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewGameHandlerClient(cc grpc.ClientConnInterface) GameHandlerClient {
	return &gameHandlerClient{cc}
}

func (c *gameHandlerClient) CreateRole(ctx context.Context, in *pb_common.CreateRoleReq, opts ...grpc.CallOption) (*pb_common.CreateRoleRsp, error) {
	out := new(pb_common.CreateRoleRsp)
	err := c.cc.Invoke(ctx, GameHandler_CreateRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameHandlerClient) LoginOnce(ctx context.Context, in *pb_common.LoginOnceReq, opts ...grpc.CallOption) (*pb_common.LoginOnceRsp, error) {
	out := new(pb_common.LoginOnceRsp)
	err := c.cc.Invoke(ctx, GameHandler_LoginOnce_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameHandlerServer is the server API for GameHandler service.
// All implementations must embed UnimplementedGameHandlerServer
// for forward compatibility
type GameHandlerServer interface {
	// 登录服创建玩家
	CreateRole(context.Context, *pb_common.CreateRoleReq) (*pb_common.CreateRoleRsp, error)
	LoginOnce(context.Context, *pb_common.LoginOnceReq) (*pb_common.LoginOnceRsp, error)
	mustEmbedUnimplementedGameHandlerServer()
}

// UnimplementedGameHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedGameHandlerServer struct {
}

func (UnimplementedGameHandlerServer) CreateRole(context.Context, *pb_common.CreateRoleReq) (*pb_common.CreateRoleRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedGameHandlerServer) LoginOnce(context.Context, *pb_common.LoginOnceReq) (*pb_common.LoginOnceRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOnce not implemented")
}
func (UnimplementedGameHandlerServer) mustEmbedUnimplementedGameHandlerServer() {}

// UnsafeGameHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameHandlerServer will
// result in compilation errors.
type UnsafeGameHandlerServer interface {
	mustEmbedUnimplementedGameHandlerServer()
}

func RegisterGameHandlerServer(s grpc.ServiceRegistrar, srv GameHandlerServer) {
	s.RegisterService(&GameHandler_ServiceDesc, srv)
}

func _GameHandler_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameHandlerServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameHandler_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameHandlerServer).CreateRole(ctx, req.(*pb_common.CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameHandler_LoginOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.LoginOnceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameHandlerServer).LoginOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameHandler_LoginOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameHandlerServer).LoginOnce(ctx, req.(*pb_common.LoginOnceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameHandler_ServiceDesc is the grpc.ServiceDesc for GameHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_game.GameHandler",
	HandlerType: (*GameHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _GameHandler_CreateRole_Handler,
		},
		{
			MethodName: "LoginOnce",
			Handler:    _GameHandler_LoginOnce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/game_server.proto",
}
