// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: services/game_server.proto

package pb_game

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameNodeService_Stream_FullMethodName     = "/pb_game.GameNodeService/Stream"
	GameNodeService_CreateRole_FullMethodName = "/pb_game.GameNodeService/CreateRole"
	GameNodeService_LoginOnce_FullMethodName  = "/pb_game.GameNodeService/LoginOnce"
)

// GameNodeServiceClient is the client API for GameNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameNodeServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket], error)
	// 登录服创建玩家
	CreateRole(ctx context.Context, in *pb_common.CreateRoleReq, opts ...grpc.CallOption) (*pb_common.CreateRoleRsp, error)
	LoginOnce(ctx context.Context, in *pb_common.LoginOnceReq, opts ...grpc.CallOption) (*pb_common.LoginOnceRsp, error)
}

type gameNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameNodeServiceClient(cc grpc.ClientConnInterface) GameNodeServiceClient {
	return &gameNodeServiceClient{cc}
}

func (c *gameNodeServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameNodeService_ServiceDesc.Streams[0], GameNodeService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[pb_common.NodePacket, pb_common.NodePacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameNodeService_StreamClient = grpc.BidiStreamingClient[pb_common.NodePacket, pb_common.NodePacket]

func (c *gameNodeServiceClient) CreateRole(ctx context.Context, in *pb_common.CreateRoleReq, opts ...grpc.CallOption) (*pb_common.CreateRoleRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb_common.CreateRoleRsp)
	err := c.cc.Invoke(ctx, GameNodeService_CreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameNodeServiceClient) LoginOnce(ctx context.Context, in *pb_common.LoginOnceReq, opts ...grpc.CallOption) (*pb_common.LoginOnceRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb_common.LoginOnceRsp)
	err := c.cc.Invoke(ctx, GameNodeService_LoginOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameNodeServiceServer is the server API for GameNodeService service.
// All implementations must embed UnimplementedGameNodeServiceServer
// for forward compatibility.
type GameNodeServiceServer interface {
	Stream(grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]) error
	// 登录服创建玩家
	CreateRole(context.Context, *pb_common.CreateRoleReq) (*pb_common.CreateRoleRsp, error)
	LoginOnce(context.Context, *pb_common.LoginOnceReq) (*pb_common.LoginOnceRsp, error)
	mustEmbedUnimplementedGameNodeServiceServer()
}

// UnimplementedGameNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameNodeServiceServer struct{}

func (UnimplementedGameNodeServiceServer) Stream(grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGameNodeServiceServer) CreateRole(context.Context, *pb_common.CreateRoleReq) (*pb_common.CreateRoleRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (UnimplementedGameNodeServiceServer) LoginOnce(context.Context, *pb_common.LoginOnceReq) (*pb_common.LoginOnceRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoginOnce not implemented")
}
func (UnimplementedGameNodeServiceServer) mustEmbedUnimplementedGameNodeServiceServer() {}
func (UnimplementedGameNodeServiceServer) testEmbeddedByValue()                         {}

// UnsafeGameNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameNodeServiceServer will
// result in compilation errors.
type UnsafeGameNodeServiceServer interface {
	mustEmbedUnimplementedGameNodeServiceServer()
}

func RegisterGameNodeServiceServer(s grpc.ServiceRegistrar, srv GameNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedGameNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameNodeService_ServiceDesc, srv)
}

func _GameNodeService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameNodeServiceServer).Stream(&grpc.GenericServerStream[pb_common.NodePacket, pb_common.NodePacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameNodeService_StreamServer = grpc.BidiStreamingServer[pb_common.NodePacket, pb_common.NodePacket]

func _GameNodeService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_CreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).CreateRole(ctx, req.(*pb_common.CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameNodeService_LoginOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.LoginOnceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameNodeServiceServer).LoginOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameNodeService_LoginOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameNodeServiceServer).LoginOnce(ctx, req.(*pb_common.LoginOnceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GameNodeService_ServiceDesc is the grpc.ServiceDesc for GameNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_game.GameNodeService",
	HandlerType: (*GameNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRole",
			Handler:    _GameNodeService_CreateRole_Handler,
		},
		{
			MethodName: "LoginOnce",
			Handler:    _GameNodeService_LoginOnce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GameNodeService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/game_server.proto",
}
