// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: hero.proto

package pb_hero

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_cultivate "server.slg.com/api/protocol/pb/pb_cultivate"
	pb_equip "server.slg.com/api/protocol/pb/pb_equip"
	pb_skill "server.slg.com/api/protocol/pb/pb_skill"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 英雄状态
type Status int32

const (
	Status_Normal  Status = 0
	Status_Injured Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Normal",
		1: "Injured",
	}
	Status_value = map[string]int32{
		"Normal":  0,
		"Injured": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_hero_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_hero_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{0}
}

// HeroInfo 英雄信息
type HeroInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId         int32                   `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                         // 配置id
	StarStage        int32                   `protobuf:"varint,2,opt,name=star_stage,json=starStage,proto3" json:"star_stage,omitempty"`                      // 星级
	AttrPoint        uint32                  `protobuf:"varint,3,opt,name=attr_point,json=attrPoint,proto3" json:"attr_point,omitempty"`                      // 属性点
	CurStatus        Status                  `protobuf:"varint,4,opt,name=cur_status,json=curStatus,proto3,enum=hero.Status" json:"cur_status,omitempty"`     // 当前状态
	CurLevel         uint32                  `protobuf:"varint,5,opt,name=cur_level,json=curLevel,proto3" json:"cur_level,omitempty"`                         // 当前等级
	CurExp           uint32                  `protobuf:"varint,6,opt,name=cur_exp,json=curExp,proto3" json:"cur_exp,omitempty"`                               // 当前经验
	AttrAttack       *pb_cultivate.Cultivate `protobuf:"bytes,11,opt,name=attr_attack,json=attrAttack,proto3" json:"attr_attack,omitempty"`                   // 攻击属性
	AttrDefense      *pb_cultivate.Cultivate `protobuf:"bytes,12,opt,name=attr_defense,json=attrDefense,proto3" json:"attr_defense,omitempty"`                // 防御属性
	AttrIntelligence *pb_cultivate.Cultivate `protobuf:"bytes,13,opt,name=attr_intelligence,json=attrIntelligence,proto3" json:"attr_intelligence,omitempty"` // 智力属性
	AttrMovement     *pb_cultivate.Cultivate `protobuf:"bytes,14,opt,name=attr_movement,json=attrMovement,proto3" json:"attr_movement,omitempty"`             // 移动属性
	AttrRelocation   *pb_cultivate.Cultivate `protobuf:"bytes,15,opt,name=attr_relocation,json=attrRelocation,proto3" json:"attr_relocation,omitempty"`       // 拆迁属性
	WageWarCityId    uint32                  `protobuf:"varint,21,opt,name=wage_war_city_id,json=wageWarCityId,proto3" json:"wage_war_city_id,omitempty"`     // 征战城市id
	Skills           []*pb_skill.Skill       `protobuf:"bytes,22,rep,name=skills,proto3" json:"skills,omitempty"`                                             // 技能信息（英雄技能槽，index0=默认技能，1/2=装配槽）
	IsAwakened       bool                    `protobuf:"varint,23,opt,name=is_awakened,json=isAwakened,proto3" json:"is_awakened,omitempty"`                  // 是否已觉醒（第三技能槽位解锁条件）
	IsLocked         bool                    `protobuf:"varint,24,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`                        // 是否锁定（锁定后不可被消耗，如升星消耗卡）
	CurTroopTypeId   int32                   `protobuf:"varint,31,opt,name=cur_troop_type_id,json=curTroopTypeId,proto3" json:"cur_troop_type_id,omitempty"`  // 当前兵种类型id
	Troops           []*pb_equip.Troop       `protobuf:"bytes,32,rep,name=troops,proto3" json:"troops,omitempty"`                                             // 所有兵种信息
}

func (x *HeroInfo) Reset() {
	*x = HeroInfo{}
	mi := &file_hero_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroInfo) ProtoMessage() {}

func (x *HeroInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroInfo.ProtoReflect.Descriptor instead.
func (*HeroInfo) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{0}
}

func (x *HeroInfo) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *HeroInfo) GetStarStage() int32 {
	if x != nil {
		return x.StarStage
	}
	return 0
}

func (x *HeroInfo) GetAttrPoint() uint32 {
	if x != nil {
		return x.AttrPoint
	}
	return 0
}

func (x *HeroInfo) GetCurStatus() Status {
	if x != nil {
		return x.CurStatus
	}
	return Status_Normal
}

func (x *HeroInfo) GetCurLevel() uint32 {
	if x != nil {
		return x.CurLevel
	}
	return 0
}

func (x *HeroInfo) GetCurExp() uint32 {
	if x != nil {
		return x.CurExp
	}
	return 0
}

func (x *HeroInfo) GetAttrAttack() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrAttack
	}
	return nil
}

func (x *HeroInfo) GetAttrDefense() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrDefense
	}
	return nil
}

func (x *HeroInfo) GetAttrIntelligence() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrIntelligence
	}
	return nil
}

func (x *HeroInfo) GetAttrMovement() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrMovement
	}
	return nil
}

func (x *HeroInfo) GetAttrRelocation() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrRelocation
	}
	return nil
}

func (x *HeroInfo) GetWageWarCityId() uint32 {
	if x != nil {
		return x.WageWarCityId
	}
	return 0
}

func (x *HeroInfo) GetSkills() []*pb_skill.Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *HeroInfo) GetIsAwakened() bool {
	if x != nil {
		return x.IsAwakened
	}
	return false
}

func (x *HeroInfo) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *HeroInfo) GetCurTroopTypeId() int32 {
	if x != nil {
		return x.CurTroopTypeId
	}
	return 0
}

func (x *HeroInfo) GetTroops() []*pb_equip.Troop {
	if x != nil {
		return x.Troops
	}
	return nil
}

// HeroList 获取英雄列表
type HeroListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeroListReq) Reset() {
	*x = HeroListReq{}
	mi := &file_hero_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroListReq) ProtoMessage() {}

func (x *HeroListReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroListReq.ProtoReflect.Descriptor instead.
func (*HeroListReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{1}
}

type HeroListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Heroes []*HeroInfo `protobuf:"bytes,1,rep,name=heroes,proto3" json:"heroes,omitempty"`
}

func (x *HeroListResp) Reset() {
	*x = HeroListResp{}
	mi := &file_hero_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroListResp) ProtoMessage() {}

func (x *HeroListResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroListResp.ProtoReflect.Descriptor instead.
func (*HeroListResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{2}
}

func (x *HeroListResp) GetHeroes() []*HeroInfo {
	if x != nil {
		return x.Heroes
	}
	return nil
}

// HeroCultivate 英雄培养
type HeroCultivateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId        uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	CultivateType uint32 `protobuf:"varint,2,opt,name=cultivate_type,json=cultivateType,proto3" json:"cultivate_type,omitempty"` // 0:攻击 1:防御 2:智力 3:速度 4:拆迁
}

func (x *HeroCultivateReq) Reset() {
	*x = HeroCultivateReq{}
	mi := &file_hero_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroCultivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroCultivateReq) ProtoMessage() {}

func (x *HeroCultivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroCultivateReq.ProtoReflect.Descriptor instead.
func (*HeroCultivateReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{3}
}

func (x *HeroCultivateReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroCultivateReq) GetCultivateType() uint32 {
	if x != nil {
		return x.CultivateType
	}
	return 0
}

type HeroCultivateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId        uint64                  `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	CultivateType uint32                  `protobuf:"varint,2,opt,name=cultivate_type,json=cultivateType,proto3" json:"cultivate_type,omitempty"`
	Attr          *pb_cultivate.Cultivate `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	AttrPoint     uint32                  `protobuf:"varint,4,opt,name=attr_point,json=attrPoint,proto3" json:"attr_point,omitempty"` // 加点后的剩余自由属性点
}

func (x *HeroCultivateResp) Reset() {
	*x = HeroCultivateResp{}
	mi := &file_hero_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroCultivateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroCultivateResp) ProtoMessage() {}

func (x *HeroCultivateResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroCultivateResp.ProtoReflect.Descriptor instead.
func (*HeroCultivateResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{4}
}

func (x *HeroCultivateResp) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroCultivateResp) GetCultivateType() uint32 {
	if x != nil {
		return x.CultivateType
	}
	return 0
}

func (x *HeroCultivateResp) GetAttr() *pb_cultivate.Cultivate {
	if x != nil {
		return x.Attr
	}
	return nil
}

func (x *HeroCultivateResp) GetAttrPoint() uint32 {
	if x != nil {
		return x.AttrPoint
	}
	return 0
}

// HeroTroopTransform 兵种转化（x 等级后选择已解锁派生类型，消耗资源）
type HeroTroopTransformReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId      uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	TroopTypeId int32  `protobuf:"varint,2,opt,name=troop_type_id,json=troopTypeId,proto3" json:"troop_type_id,omitempty"` // 目标派生兵种类型
}

func (x *HeroTroopTransformReq) Reset() {
	*x = HeroTroopTransformReq{}
	mi := &file_hero_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroTroopTransformReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroTroopTransformReq) ProtoMessage() {}

func (x *HeroTroopTransformReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroTroopTransformReq.ProtoReflect.Descriptor instead.
func (*HeroTroopTransformReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{5}
}

func (x *HeroTroopTransformReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroTroopTransformReq) GetTroopTypeId() int32 {
	if x != nil {
		return x.TroopTypeId
	}
	return 0
}

type HeroTroopTransformResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId         uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	CurTroopTypeId int32  `protobuf:"varint,2,opt,name=cur_troop_type_id,json=curTroopTypeId,proto3" json:"cur_troop_type_id,omitempty"` // 转化后的当前兵种
}

func (x *HeroTroopTransformResp) Reset() {
	*x = HeroTroopTransformResp{}
	mi := &file_hero_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroTroopTransformResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroTroopTransformResp) ProtoMessage() {}

func (x *HeroTroopTransformResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroTroopTransformResp.ProtoReflect.Descriptor instead.
func (*HeroTroopTransformResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{6}
}

func (x *HeroTroopTransformResp) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroTroopTransformResp) GetCurTroopTypeId() int32 {
	if x != nil {
		return x.CurTroopTypeId
	}
	return 0
}

// HeroTroopUnlock 扩展兵种（使用道具解锁新的可选派生类型）
type HeroTroopUnlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId      uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	TroopTypeId int32  `protobuf:"varint,2,opt,name=troop_type_id,json=troopTypeId,proto3" json:"troop_type_id,omitempty"` // 要解锁的派生兵种类型
}

func (x *HeroTroopUnlockReq) Reset() {
	*x = HeroTroopUnlockReq{}
	mi := &file_hero_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroTroopUnlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroTroopUnlockReq) ProtoMessage() {}

func (x *HeroTroopUnlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroTroopUnlockReq.ProtoReflect.Descriptor instead.
func (*HeroTroopUnlockReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{7}
}

func (x *HeroTroopUnlockReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroTroopUnlockReq) GetTroopTypeId() int32 {
	if x != nil {
		return x.TroopTypeId
	}
	return 0
}

type HeroTroopUnlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId      uint64            `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	TroopTypeId int32             `protobuf:"varint,2,opt,name=troop_type_id,json=troopTypeId,proto3" json:"troop_type_id,omitempty"`
	Troops      []*pb_equip.Troop `protobuf:"bytes,3,rep,name=troops,proto3" json:"troops,omitempty"` // 解锁后的兵种列表
}

func (x *HeroTroopUnlockResp) Reset() {
	*x = HeroTroopUnlockResp{}
	mi := &file_hero_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroTroopUnlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroTroopUnlockResp) ProtoMessage() {}

func (x *HeroTroopUnlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroTroopUnlockResp.ProtoReflect.Descriptor instead.
func (*HeroTroopUnlockResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{8}
}

func (x *HeroTroopUnlockResp) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroTroopUnlockResp) GetTroopTypeId() int32 {
	if x != nil {
		return x.TroopTypeId
	}
	return 0
}

func (x *HeroTroopUnlockResp) GetTroops() []*pb_equip.Troop {
	if x != nil {
		return x.Troops
	}
	return nil
}

// HeroSkillUpgrade 技能升级
//
// 升级英雄身上（EquipSkills 槽位）的技能等级，消耗道具。不改变技能库(hero_skills)等级。
type HeroSkillUpgradeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"` // 英雄实例ID
	SlotId int32  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 技能槽位（1/2；0=默认技能不可升级）
}

func (x *HeroSkillUpgradeReq) Reset() {
	*x = HeroSkillUpgradeReq{}
	mi := &file_hero_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroSkillUpgradeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroSkillUpgradeReq) ProtoMessage() {}

func (x *HeroSkillUpgradeReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroSkillUpgradeReq.ProtoReflect.Descriptor instead.
func (*HeroSkillUpgradeReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{9}
}

func (x *HeroSkillUpgradeReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroSkillUpgradeReq) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type HeroSkillUpgradeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skill *pb_skill.Skill `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"` // 升级后的槽位技能（含新 level）
}

func (x *HeroSkillUpgradeResp) Reset() {
	*x = HeroSkillUpgradeResp{}
	mi := &file_hero_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroSkillUpgradeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroSkillUpgradeResp) ProtoMessage() {}

func (x *HeroSkillUpgradeResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroSkillUpgradeResp.ProtoReflect.Descriptor instead.
func (*HeroSkillUpgradeResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{10}
}

func (x *HeroSkillUpgradeResp) GetSkill() *pb_skill.Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

// HeroUpgradeStar 英雄升星
//
// 指定待升星英雄，消耗一张与之相同配置（hero_conf_id）的英雄卡，升 1 星。
// 星级上限由服务端常量配置。消耗的英雄卡配置记录进养成消耗记录。
type HeroUpgradeStarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"` // 待升星英雄实例ID
}

func (x *HeroUpgradeStarReq) Reset() {
	*x = HeroUpgradeStarReq{}
	mi := &file_hero_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUpgradeStarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpgradeStarReq) ProtoMessage() {}

func (x *HeroUpgradeStarReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpgradeStarReq.ProtoReflect.Descriptor instead.
func (*HeroUpgradeStarReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{11}
}

func (x *HeroUpgradeStarReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

type HeroUpgradeStarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId    uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`          // 升星英雄实例ID
	StarStage int32  `protobuf:"varint,2,opt,name=star_stage,json=starStage,proto3" json:"star_stage,omitempty"` // 升星后星级
}

func (x *HeroUpgradeStarResp) Reset() {
	*x = HeroUpgradeStarResp{}
	mi := &file_hero_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUpgradeStarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpgradeStarResp) ProtoMessage() {}

func (x *HeroUpgradeStarResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpgradeStarResp.ProtoReflect.Descriptor instead.
func (*HeroUpgradeStarResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{12}
}

func (x *HeroUpgradeStarResp) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroUpgradeStarResp) GetStarStage() int32 {
	if x != nil {
		return x.StarStage
	}
	return 0
}

// HeroLock 锁定英雄：锁定后不可被消耗（升星消耗卡等）
type HeroLockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
}

func (x *HeroLockReq) Reset() {
	*x = HeroLockReq{}
	mi := &file_hero_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroLockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroLockReq) ProtoMessage() {}

func (x *HeroLockReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroLockReq.ProtoReflect.Descriptor instead.
func (*HeroLockReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{13}
}

func (x *HeroLockReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

type HeroLockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId   uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	IsLocked bool   `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"` // 锁定后 true
}

func (x *HeroLockResp) Reset() {
	*x = HeroLockResp{}
	mi := &file_hero_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroLockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroLockResp) ProtoMessage() {}

func (x *HeroLockResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroLockResp.ProtoReflect.Descriptor instead.
func (*HeroLockResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{14}
}

func (x *HeroLockResp) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroLockResp) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

// HeroUnlock 解锁英雄
type HeroUnlockReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
}

func (x *HeroUnlockReq) Reset() {
	*x = HeroUnlockReq{}
	mi := &file_hero_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUnlockReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUnlockReq) ProtoMessage() {}

func (x *HeroUnlockReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUnlockReq.ProtoReflect.Descriptor instead.
func (*HeroUnlockReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{15}
}

func (x *HeroUnlockReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

type HeroUnlockResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId   uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	IsLocked bool   `protobuf:"varint,2,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"` // 解锁后 false
}

func (x *HeroUnlockResp) Reset() {
	*x = HeroUnlockResp{}
	mi := &file_hero_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUnlockResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUnlockResp) ProtoMessage() {}

func (x *HeroUnlockResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUnlockResp.ProtoReflect.Descriptor instead.
func (*HeroUnlockResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{16}
}

func (x *HeroUnlockResp) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroUnlockResp) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

// HeroEquipSkill 装配技能
//
// 将角色技能库（hero_skills）的技能放入英雄技能槽。装配前校验槽位可用性
// （slot1=英雄等级达标；slot2=等级达标+已觉醒）与技能库状态（存在/未装配他处/装配次数未满）。
type HeroEquipSkillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId      uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`                  // 英雄实例ID
	SlotId      int32  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                  // 技能槽位（1/2）
	SkillConfId int32  `protobuf:"varint,3,opt,name=skill_conf_id,json=skillConfId,proto3" json:"skill_conf_id,omitempty"` // 技能库技能配置ID
}

func (x *HeroEquipSkillReq) Reset() {
	*x = HeroEquipSkillReq{}
	mi := &file_hero_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroEquipSkillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroEquipSkillReq) ProtoMessage() {}

func (x *HeroEquipSkillReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroEquipSkillReq.ProtoReflect.Descriptor instead.
func (*HeroEquipSkillReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{17}
}

func (x *HeroEquipSkillReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroEquipSkillReq) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *HeroEquipSkillReq) GetSkillConfId() int32 {
	if x != nil {
		return x.SkillConfId
	}
	return 0
}

type HeroEquipSkillResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skills []*pb_skill.Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"` // 装配后的英雄技能槽
}

func (x *HeroEquipSkillResp) Reset() {
	*x = HeroEquipSkillResp{}
	mi := &file_hero_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroEquipSkillResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroEquipSkillResp) ProtoMessage() {}

func (x *HeroEquipSkillResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroEquipSkillResp.ProtoReflect.Descriptor instead.
func (*HeroEquipSkillResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{18}
}

func (x *HeroEquipSkillResp) GetSkills() []*pb_skill.Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// HeroUnequipSkill 拆卸技能
//
// 从英雄技能槽移除技能，清空技能库装配记录，按已升级等级返还部分升级资源。
type HeroUnequipSkillReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId uint64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"` // 英雄实例ID
	SlotId int32  `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"` // 技能槽位（1/2）
}

func (x *HeroUnequipSkillReq) Reset() {
	*x = HeroUnequipSkillReq{}
	mi := &file_hero_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUnequipSkillReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUnequipSkillReq) ProtoMessage() {}

func (x *HeroUnequipSkillReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUnequipSkillReq.ProtoReflect.Descriptor instead.
func (*HeroUnequipSkillReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{19}
}

func (x *HeroUnequipSkillReq) GetHeroId() uint64 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroUnequipSkillReq) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type HeroUnequipSkillResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skills      []*pb_skill.Skill `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`                               // 拆卸后的英雄技能槽
	RefundCount int64             `protobuf:"varint,2,opt,name=refund_count,json=refundCount,proto3" json:"refund_count,omitempty"` // 返还的升级道具数量
}

func (x *HeroUnequipSkillResp) Reset() {
	*x = HeroUnequipSkillResp{}
	mi := &file_hero_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUnequipSkillResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUnequipSkillResp) ProtoMessage() {}

func (x *HeroUnequipSkillResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUnequipSkillResp.ProtoReflect.Descriptor instead.
func (*HeroUnequipSkillResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{20}
}

func (x *HeroUnequipSkillResp) GetSkills() []*pb_skill.Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *HeroUnequipSkillResp) GetRefundCount() int64 {
	if x != nil {
		return x.RefundCount
	}
	return 0
}

var File_hero_proto protoreflect.FileDescriptor

var file_hero_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x65,
	0x72, 0x6f, 0x1a, 0x0f, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd3, 0x05,
	0x0a, 0x08, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x68, 0x65, 0x72, 0x6f,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x63, 0x75, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x75, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x63, 0x75, 0x72, 0x45, 0x78, 0x70, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x72,
	0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x75, 0x6c, 0x74, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12,
	0x37, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x43, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x61, 0x74, 0x74,
	0x72, 0x44, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x11, 0x61, 0x74, 0x74, 0x72,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x43, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x10, 0x61, 0x74, 0x74, 0x72, 0x49,
	0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x61,
	0x74, 0x74, 0x72, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43,
	0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x4d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x72,
	0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x75, 0x6c, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0e, 0x61, 0x74, 0x74, 0x72, 0x52, 0x65, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x10, 0x77, 0x61, 0x67, 0x65, 0x5f, 0x77, 0x61,
	0x72, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x77, 0x61, 0x67, 0x65, 0x57, 0x61, 0x72, 0x43, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x16, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x77, 0x61, 0x6b, 0x65,
	0x6e, 0x65, 0x64, 0x18, 0x17, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x77, 0x61,
	0x6b, 0x65, 0x6e, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x18, 0x18, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b,
	0x65, 0x64, 0x12, 0x29, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x5f, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x63,
	0x75, 0x72, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x06, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x73, 0x18, 0x20, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x52, 0x06, 0x74, 0x72, 0x6f,
	0x6f, 0x70, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x48, 0x65, 0x72, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x22, 0x36, 0x0a, 0x0c, 0x48, 0x65, 0x72, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x10, 0x48, 0x65,
	0x72, 0x6f, 0x43, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x6c, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x9c,
	0x01, 0x0a, 0x11, 0x48, 0x65, 0x72, 0x6f, 0x43, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x61, 0x74, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43,
	0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x22, 0x54, 0x0a,
	0x15, 0x48, 0x65, 0x72, 0x6f, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0d, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x16, 0x48, 0x65, 0x72, 0x6f, 0x54, 0x72, 0x6f, 0x6f, 0x70,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a,
	0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x5f, 0x74, 0x72,
	0x6f, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x63, 0x75, 0x72, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x64, 0x22, 0x51, 0x0a, 0x12, 0x48, 0x65, 0x72, 0x6f, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x55, 0x6e,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x13, 0x48, 0x65, 0x72, 0x6f, 0x54, 0x72, 0x6f, 0x6f,
	0x70, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x68,
	0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65,
	0x72, 0x6f, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x72, 0x6f,
	0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x72, 0x6f, 0x6f,
	0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x2e, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x52, 0x06, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x73, 0x22, 0x47,
	0x0a, 0x13, 0x48, 0x65, 0x72, 0x6f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x55, 0x70, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x14, 0x48, 0x65, 0x72, 0x6f, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x22, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x05, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x22, 0x2d, 0x0a, 0x12, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72,
	0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f,
	0x49, 0x64, 0x22, 0x4d, 0x0a, 0x13, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72,
	0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x53, 0x74, 0x61, 0x67,
	0x65, 0x22, 0x26, 0x0a, 0x0b, 0x48, 0x65, 0x72, 0x6f, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x0c, 0x48, 0x65, 0x72,
	0x6f, 0x4c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72,
	0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x22,
	0x28, 0x0a, 0x0d, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x0e, 0x48, 0x65, 0x72,
	0x6f, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x68,
	0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65,
	0x72, 0x6f, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x22, 0x69, 0x0a, 0x11, 0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x6b,
	0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x12,
	0x48, 0x65, 0x72, 0x6f, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x22, 0x47, 0x0a, 0x13, 0x48, 0x65, 0x72, 0x6f,
	0x55, 0x6e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49,
	0x64, 0x22, 0x5f, 0x0a, 0x14, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x6e, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x2a, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x6a, 0x75,
	0x72, 0x65, 0x64, 0x10, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x73, 0x6c, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x68, 0x65, 0x72, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hero_proto_rawDescOnce sync.Once
	file_hero_proto_rawDescData = file_hero_proto_rawDesc
)

func file_hero_proto_rawDescGZIP() []byte {
	file_hero_proto_rawDescOnce.Do(func() {
		file_hero_proto_rawDescData = protoimpl.X.CompressGZIP(file_hero_proto_rawDescData)
	})
	return file_hero_proto_rawDescData
}

var file_hero_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hero_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_hero_proto_goTypes = []any{
	(Status)(0),                    // 0: hero.Status
	(*HeroInfo)(nil),               // 1: hero.HeroInfo
	(*HeroListReq)(nil),            // 2: hero.HeroListReq
	(*HeroListResp)(nil),           // 3: hero.HeroListResp
	(*HeroCultivateReq)(nil),       // 4: hero.HeroCultivateReq
	(*HeroCultivateResp)(nil),      // 5: hero.HeroCultivateResp
	(*HeroTroopTransformReq)(nil),  // 6: hero.HeroTroopTransformReq
	(*HeroTroopTransformResp)(nil), // 7: hero.HeroTroopTransformResp
	(*HeroTroopUnlockReq)(nil),     // 8: hero.HeroTroopUnlockReq
	(*HeroTroopUnlockResp)(nil),    // 9: hero.HeroTroopUnlockResp
	(*HeroSkillUpgradeReq)(nil),    // 10: hero.HeroSkillUpgradeReq
	(*HeroSkillUpgradeResp)(nil),   // 11: hero.HeroSkillUpgradeResp
	(*HeroUpgradeStarReq)(nil),     // 12: hero.HeroUpgradeStarReq
	(*HeroUpgradeStarResp)(nil),    // 13: hero.HeroUpgradeStarResp
	(*HeroLockReq)(nil),            // 14: hero.HeroLockReq
	(*HeroLockResp)(nil),           // 15: hero.HeroLockResp
	(*HeroUnlockReq)(nil),          // 16: hero.HeroUnlockReq
	(*HeroUnlockResp)(nil),         // 17: hero.HeroUnlockResp
	(*HeroEquipSkillReq)(nil),      // 18: hero.HeroEquipSkillReq
	(*HeroEquipSkillResp)(nil),     // 19: hero.HeroEquipSkillResp
	(*HeroUnequipSkillReq)(nil),    // 20: hero.HeroUnequipSkillReq
	(*HeroUnequipSkillResp)(nil),   // 21: hero.HeroUnequipSkillResp
	(*pb_cultivate.Cultivate)(nil), // 22: cultivate.Cultivate
	(*pb_skill.Skill)(nil),         // 23: skill.Skill
	(*pb_equip.Troop)(nil),         // 24: equip.Troop
}
var file_hero_proto_depIdxs = []int32{
	0,  // 0: hero.HeroInfo.cur_status:type_name -> hero.Status
	22, // 1: hero.HeroInfo.attr_attack:type_name -> cultivate.Cultivate
	22, // 2: hero.HeroInfo.attr_defense:type_name -> cultivate.Cultivate
	22, // 3: hero.HeroInfo.attr_intelligence:type_name -> cultivate.Cultivate
	22, // 4: hero.HeroInfo.attr_movement:type_name -> cultivate.Cultivate
	22, // 5: hero.HeroInfo.attr_relocation:type_name -> cultivate.Cultivate
	23, // 6: hero.HeroInfo.skills:type_name -> skill.Skill
	24, // 7: hero.HeroInfo.troops:type_name -> equip.Troop
	1,  // 8: hero.HeroListResp.heroes:type_name -> hero.HeroInfo
	22, // 9: hero.HeroCultivateResp.attr:type_name -> cultivate.Cultivate
	24, // 10: hero.HeroTroopUnlockResp.troops:type_name -> equip.Troop
	23, // 11: hero.HeroSkillUpgradeResp.skill:type_name -> skill.Skill
	23, // 12: hero.HeroEquipSkillResp.skills:type_name -> skill.Skill
	23, // 13: hero.HeroUnequipSkillResp.skills:type_name -> skill.Skill
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_hero_proto_init() }
func file_hero_proto_init() {
	if File_hero_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hero_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hero_proto_goTypes,
		DependencyIndexes: file_hero_proto_depIdxs,
		EnumInfos:         file_hero_proto_enumTypes,
		MessageInfos:      file_hero_proto_msgTypes,
	}.Build()
	File_hero_proto = out.File
	file_hero_proto_rawDesc = nil
	file_hero_proto_goTypes = nil
	file_hero_proto_depIdxs = nil
}
