// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: hero.proto

package pb_hero

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_cultivate "server.slg.com/api/protocol/pb/pb_cultivate"
	pb_equip "server.slg.com/api/protocol/pb/pb_equip"
	pb_skill "server.slg.com/api/protocol/pb/pb_skill"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 英雄状态
type Status int32

const (
	Status_Normal  Status = 0
	Status_Injured Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Normal",
		1: "Injured",
	}
	Status_value = map[string]int32{
		"Normal":  0,
		"Injured": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_hero_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_hero_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{0}
}

// HeroInfo 英雄信息
type HeroInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId         int32                   `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                         // 配置id
	StarStage        int32                   `protobuf:"varint,2,opt,name=star_stage,json=starStage,proto3" json:"star_stage,omitempty"`                      // 星级
	AttrPoint        uint32                  `protobuf:"varint,3,opt,name=attr_point,json=attrPoint,proto3" json:"attr_point,omitempty"`                      // 属性点
	CurStatus        Status                  `protobuf:"varint,4,opt,name=cur_status,json=curStatus,proto3,enum=hero.Status" json:"cur_status,omitempty"`     // 当前状态
	CurLevel         uint32                  `protobuf:"varint,5,opt,name=cur_level,json=curLevel,proto3" json:"cur_level,omitempty"`                         // 当前等级
	CurExp           uint32                  `protobuf:"varint,6,opt,name=cur_exp,json=curExp,proto3" json:"cur_exp,omitempty"`                               // 当前经验
	AttrAttack       *pb_cultivate.Cultivate `protobuf:"bytes,11,opt,name=attr_attack,json=attrAttack,proto3" json:"attr_attack,omitempty"`                   // 攻击属性
	AttrDefense      *pb_cultivate.Cultivate `protobuf:"bytes,12,opt,name=attr_defense,json=attrDefense,proto3" json:"attr_defense,omitempty"`                // 防御属性
	AttrIntelligence *pb_cultivate.Cultivate `protobuf:"bytes,13,opt,name=attr_intelligence,json=attrIntelligence,proto3" json:"attr_intelligence,omitempty"` // 智力属性
	AttrMovement     *pb_cultivate.Cultivate `protobuf:"bytes,14,opt,name=attr_movement,json=attrMovement,proto3" json:"attr_movement,omitempty"`             // 移动属性
	AttrRelocation   *pb_cultivate.Cultivate `protobuf:"bytes,15,opt,name=attr_relocation,json=attrRelocation,proto3" json:"attr_relocation,omitempty"`       // 拆迁属性
	WageWarCityId    uint32                  `protobuf:"varint,21,opt,name=wage_war_city_id,json=wageWarCityId,proto3" json:"wage_war_city_id,omitempty"`     // 征战城市id
	Skills           []*pb_skill.Skill       `protobuf:"bytes,22,rep,name=skills,proto3" json:"skills,omitempty"`                                             // 技能信息
	CurTroopTypeId   int32                   `protobuf:"varint,31,opt,name=cur_troop_type_id,json=curTroopTypeId,proto3" json:"cur_troop_type_id,omitempty"`  // 当前兵种类型id
	Troops           []*pb_equip.Troop       `protobuf:"bytes,32,rep,name=troops,proto3" json:"troops,omitempty"`                                             // 所有兵种信息
}

func (x *HeroInfo) Reset() {
	*x = HeroInfo{}
	mi := &file_hero_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroInfo) ProtoMessage() {}

func (x *HeroInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroInfo.ProtoReflect.Descriptor instead.
func (*HeroInfo) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{0}
}

func (x *HeroInfo) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *HeroInfo) GetStarStage() int32 {
	if x != nil {
		return x.StarStage
	}
	return 0
}

func (x *HeroInfo) GetAttrPoint() uint32 {
	if x != nil {
		return x.AttrPoint
	}
	return 0
}

func (x *HeroInfo) GetCurStatus() Status {
	if x != nil {
		return x.CurStatus
	}
	return Status_Normal
}

func (x *HeroInfo) GetCurLevel() uint32 {
	if x != nil {
		return x.CurLevel
	}
	return 0
}

func (x *HeroInfo) GetCurExp() uint32 {
	if x != nil {
		return x.CurExp
	}
	return 0
}

func (x *HeroInfo) GetAttrAttack() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrAttack
	}
	return nil
}

func (x *HeroInfo) GetAttrDefense() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrDefense
	}
	return nil
}

func (x *HeroInfo) GetAttrIntelligence() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrIntelligence
	}
	return nil
}

func (x *HeroInfo) GetAttrMovement() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrMovement
	}
	return nil
}

func (x *HeroInfo) GetAttrRelocation() *pb_cultivate.Cultivate {
	if x != nil {
		return x.AttrRelocation
	}
	return nil
}

func (x *HeroInfo) GetWageWarCityId() uint32 {
	if x != nil {
		return x.WageWarCityId
	}
	return 0
}

func (x *HeroInfo) GetSkills() []*pb_skill.Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *HeroInfo) GetCurTroopTypeId() int32 {
	if x != nil {
		return x.CurTroopTypeId
	}
	return 0
}

func (x *HeroInfo) GetTroops() []*pb_equip.Troop {
	if x != nil {
		return x.Troops
	}
	return nil
}

// HeroList 获取英雄列表
type HeroListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeroListReq) Reset() {
	*x = HeroListReq{}
	mi := &file_hero_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroListReq) ProtoMessage() {}

func (x *HeroListReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroListReq.ProtoReflect.Descriptor instead.
func (*HeroListReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{1}
}

type HeroListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Heroes []*HeroInfo `protobuf:"bytes,1,rep,name=heroes,proto3" json:"heroes,omitempty"`
}

func (x *HeroListResp) Reset() {
	*x = HeroListResp{}
	mi := &file_hero_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroListResp) ProtoMessage() {}

func (x *HeroListResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroListResp.ProtoReflect.Descriptor instead.
func (*HeroListResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{2}
}

func (x *HeroListResp) GetHeroes() []*HeroInfo {
	if x != nil {
		return x.Heroes
	}
	return nil
}

// HeroUpgradeLevelReq 英雄升级
type HeroUpgradeLevelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId int32 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
}

func (x *HeroUpgradeLevelReq) Reset() {
	*x = HeroUpgradeLevelReq{}
	mi := &file_hero_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUpgradeLevelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpgradeLevelReq) ProtoMessage() {}

func (x *HeroUpgradeLevelReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpgradeLevelReq.ProtoReflect.Descriptor instead.
func (*HeroUpgradeLevelReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{3}
}

func (x *HeroUpgradeLevelReq) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

type HeroUpgradeLevelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId int32  `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	Level  uint32 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *HeroUpgradeLevelResp) Reset() {
	*x = HeroUpgradeLevelResp{}
	mi := &file_hero_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroUpgradeLevelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpgradeLevelResp) ProtoMessage() {}

func (x *HeroUpgradeLevelResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpgradeLevelResp.ProtoReflect.Descriptor instead.
func (*HeroUpgradeLevelResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{4}
}

func (x *HeroUpgradeLevelResp) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroUpgradeLevelResp) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// HeroCultivate 英雄培养
type HeroCultivateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId        int32  `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	CultivateType uint32 `protobuf:"varint,2,opt,name=cultivate_type,json=cultivateType,proto3" json:"cultivate_type,omitempty"` // 0:攻击 1:防御 2:智力 3:速度 4:拆迁
}

func (x *HeroCultivateReq) Reset() {
	*x = HeroCultivateReq{}
	mi := &file_hero_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroCultivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroCultivateReq) ProtoMessage() {}

func (x *HeroCultivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroCultivateReq.ProtoReflect.Descriptor instead.
func (*HeroCultivateReq) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{5}
}

func (x *HeroCultivateReq) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroCultivateReq) GetCultivateType() uint32 {
	if x != nil {
		return x.CultivateType
	}
	return 0
}

type HeroCultivateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroId        int32                   `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	CultivateType uint32                  `protobuf:"varint,2,opt,name=cultivate_type,json=cultivateType,proto3" json:"cultivate_type,omitempty"`
	Attr          *pb_cultivate.Cultivate `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
}

func (x *HeroCultivateResp) Reset() {
	*x = HeroCultivateResp{}
	mi := &file_hero_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroCultivateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroCultivateResp) ProtoMessage() {}

func (x *HeroCultivateResp) ProtoReflect() protoreflect.Message {
	mi := &file_hero_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroCultivateResp.ProtoReflect.Descriptor instead.
func (*HeroCultivateResp) Descriptor() ([]byte, []int) {
	return file_hero_proto_rawDescGZIP(), []int{6}
}

func (x *HeroCultivateResp) GetHeroId() int32 {
	if x != nil {
		return x.HeroId
	}
	return 0
}

func (x *HeroCultivateResp) GetCultivateType() uint32 {
	if x != nil {
		return x.CultivateType
	}
	return 0
}

func (x *HeroCultivateResp) GetAttr() *pb_cultivate.Cultivate {
	if x != nil {
		return x.Attr
	}
	return nil
}

var File_hero_proto protoreflect.FileDescriptor

var file_hero_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x68, 0x65,
	0x72, 0x6f, 0x1a, 0x0f, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x05,
	0x0a, 0x08, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x5f,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61,
	0x72, 0x53, 0x74, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x68, 0x65, 0x72, 0x6f,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x63, 0x75, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x75, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x5f, 0x65, 0x78, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x63, 0x75, 0x72, 0x45, 0x78, 0x70, 0x12, 0x35, 0x0a, 0x0b, 0x61, 0x74, 0x74, 0x72,
	0x5f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x75, 0x6c, 0x74, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12,
	0x37, 0x0a, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x64, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x2e, 0x43, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x61, 0x74, 0x74,
	0x72, 0x44, 0x65, 0x66, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x11, 0x61, 0x74, 0x74, 0x72,
	0x5f, 0x69, 0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e,
	0x43, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x10, 0x61, 0x74, 0x74, 0x72, 0x49,
	0x6e, 0x74, 0x65, 0x6c, 0x6c, 0x69, 0x67, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x61,
	0x74, 0x74, 0x72, 0x5f, 0x6d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43,
	0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0c, 0x61, 0x74, 0x74, 0x72, 0x4d, 0x6f,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x72,
	0x65, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x75, 0x6c, 0x74,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x0e, 0x61, 0x74, 0x74, 0x72, 0x52, 0x65, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x10, 0x77, 0x61, 0x67, 0x65, 0x5f, 0x77, 0x61,
	0x72, 0x5f, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x77, 0x61, 0x67, 0x65, 0x57, 0x61, 0x72, 0x43, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x16, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b,
	0x69, 0x6c, 0x6c, 0x73, 0x12, 0x29, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x5f, 0x74, 0x72, 0x6f, 0x6f,
	0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x63, 0x75, 0x72, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12,
	0x24, 0x0a, 0x06, 0x74, 0x72, 0x6f, 0x6f, 0x70, 0x73, 0x18, 0x20, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x54, 0x72, 0x6f, 0x6f, 0x70, 0x52, 0x06, 0x74,
	0x72, 0x6f, 0x6f, 0x70, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x48, 0x65, 0x72, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x22, 0x36, 0x0a, 0x0c, 0x48, 0x65, 0x72, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x48, 0x65, 0x72, 0x6f,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x65, 0x73, 0x22, 0x2e, 0x0a, 0x13,
	0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x14,
	0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x22, 0x52, 0x0a, 0x10, 0x48, 0x65, 0x72, 0x6f, 0x43, 0x75, 0x6c, 0x74, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x72, 0x6f, 0x49, 0x64,
	0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7d, 0x0a, 0x11, 0x48, 0x65, 0x72, 0x6f, 0x43,
	0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x17, 0x0a, 0x07,
	0x68, 0x65, 0x72, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68,
	0x65, 0x72, 0x6f, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63,
	0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x04,
	0x61, 0x74, 0x74, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x75, 0x6c,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x75, 0x6c, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x52, 0x04, 0x61, 0x74, 0x74, 0x72, 0x2a, 0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x49, 0x6e, 0x6a, 0x75, 0x72, 0x65, 0x64, 0x10, 0x01, 0x42, 0x28, 0x5a, 0x26, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x68,
	0x65, 0x72, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hero_proto_rawDescOnce sync.Once
	file_hero_proto_rawDescData = file_hero_proto_rawDesc
)

func file_hero_proto_rawDescGZIP() []byte {
	file_hero_proto_rawDescOnce.Do(func() {
		file_hero_proto_rawDescData = protoimpl.X.CompressGZIP(file_hero_proto_rawDescData)
	})
	return file_hero_proto_rawDescData
}

var file_hero_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hero_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hero_proto_goTypes = []any{
	(Status)(0),                    // 0: hero.Status
	(*HeroInfo)(nil),               // 1: hero.HeroInfo
	(*HeroListReq)(nil),            // 2: hero.HeroListReq
	(*HeroListResp)(nil),           // 3: hero.HeroListResp
	(*HeroUpgradeLevelReq)(nil),    // 4: hero.HeroUpgradeLevelReq
	(*HeroUpgradeLevelResp)(nil),   // 5: hero.HeroUpgradeLevelResp
	(*HeroCultivateReq)(nil),       // 6: hero.HeroCultivateReq
	(*HeroCultivateResp)(nil),      // 7: hero.HeroCultivateResp
	(*pb_cultivate.Cultivate)(nil), // 8: cultivate.Cultivate
	(*pb_skill.Skill)(nil),         // 9: skill.Skill
	(*pb_equip.Troop)(nil),         // 10: equip.Troop
}
var file_hero_proto_depIdxs = []int32{
	0,  // 0: hero.HeroInfo.cur_status:type_name -> hero.Status
	8,  // 1: hero.HeroInfo.attr_attack:type_name -> cultivate.Cultivate
	8,  // 2: hero.HeroInfo.attr_defense:type_name -> cultivate.Cultivate
	8,  // 3: hero.HeroInfo.attr_intelligence:type_name -> cultivate.Cultivate
	8,  // 4: hero.HeroInfo.attr_movement:type_name -> cultivate.Cultivate
	8,  // 5: hero.HeroInfo.attr_relocation:type_name -> cultivate.Cultivate
	9,  // 6: hero.HeroInfo.skills:type_name -> skill.Skill
	10, // 7: hero.HeroInfo.troops:type_name -> equip.Troop
	1,  // 8: hero.HeroListResp.heroes:type_name -> hero.HeroInfo
	8,  // 9: hero.HeroCultivateResp.attr:type_name -> cultivate.Cultivate
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_hero_proto_init() }
func file_hero_proto_init() {
	if File_hero_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hero_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hero_proto_goTypes,
		DependencyIndexes: file_hero_proto_depIdxs,
		EnumInfos:         file_hero_proto_enumTypes,
		MessageInfos:      file_hero_proto_msgTypes,
	}.Build()
	File_hero_proto = out.File
	file_hero_proto_rawDesc = nil
	file_hero_proto_goTypes = nil
	file_hero_proto_depIdxs = nil
}
