// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: skill.proto

package pb_skill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Skill 技能
type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId       int32 `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                // 配置id
	SlotId         int32 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`                      // 技能槽位
	Level          int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                      // 技能等级
	Research_Level int32 `protobuf:"varint,4,opt,name=research_Level,json=researchLevel,proto3" json:"research_Level,omitempty"` // 研究等级
	IsUnlock       bool  `protobuf:"varint,5,opt,name=is_unlock,json=isUnlock,proto3" json:"is_unlock,omitempty"`                // 是否已经解锁
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *Skill) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *Skill) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Skill) GetResearch_Level() int32 {
	if x != nil {
		return x.Research_Level
	}
	return 0
}

func (x *Skill) GetIsUnlock() bool {
	if x != nil {
		return x.IsUnlock
	}
	return false
}

type SkillCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId        int32                `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                     // 配置id
	CollectionLevel []*pb_common.Int32KV `protobuf:"bytes,2,rep,name=collection_level,json=collectionLevel,proto3" json:"collection_level,omitempty"` // 收集进度（K=道具配置ID，V=已收集数量）
	IsUnlock        bool                 `protobuf:"varint,3,opt,name=is_unlock,json=isUnlock,proto3" json:"is_unlock,omitempty"`                     // 是否已解锁
}

func (x *SkillCollection) Reset() {
	*x = SkillCollection{}
	mi := &file_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCollection) ProtoMessage() {}

func (x *SkillCollection) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCollection.ProtoReflect.Descriptor instead.
func (*SkillCollection) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{1}
}

func (x *SkillCollection) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *SkillCollection) GetCollectionLevel() []*pb_common.Int32KV {
	if x != nil {
		return x.CollectionLevel
	}
	return nil
}

func (x *SkillCollection) GetIsUnlock() bool {
	if x != nil {
		return x.IsUnlock
	}
	return false
}

// SkillCollectionActivate 技能收藏激活（分次收集）
//
// 消耗配置指定道具推进收集进度，全部达标后解锁对应技能。
type SkillCollectionActivateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkillConfId int32 `protobuf:"varint,1,opt,name=skill_conf_id,json=skillConfId,proto3" json:"skill_conf_id,omitempty"` // 收藏对应技能配置ID
	ItemConfId  int32 `protobuf:"varint,2,opt,name=item_conf_id,json=itemConfId,proto3" json:"item_conf_id,omitempty"`    // 消耗的道具配置ID（须为该收藏配置所需）
	Count       int64 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                                  // 消耗数量
}

func (x *SkillCollectionActivateReq) Reset() {
	*x = SkillCollectionActivateReq{}
	mi := &file_skill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillCollectionActivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCollectionActivateReq) ProtoMessage() {}

func (x *SkillCollectionActivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCollectionActivateReq.ProtoReflect.Descriptor instead.
func (*SkillCollectionActivateReq) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{2}
}

func (x *SkillCollectionActivateReq) GetSkillConfId() int32 {
	if x != nil {
		return x.SkillConfId
	}
	return 0
}

func (x *SkillCollectionActivateReq) GetItemConfId() int32 {
	if x != nil {
		return x.ItemConfId
	}
	return 0
}

func (x *SkillCollectionActivateReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SkillCollectionActivateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Collection *SkillCollection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"` // 激活后的收藏状态
}

func (x *SkillCollectionActivateResp) Reset() {
	*x = SkillCollectionActivateResp{}
	mi := &file_skill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillCollectionActivateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillCollectionActivateResp) ProtoMessage() {}

func (x *SkillCollectionActivateResp) ProtoReflect() protoreflect.Message {
	mi := &file_skill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillCollectionActivateResp.ProtoReflect.Descriptor instead.
func (*SkillCollectionActivateResp) Descriptor() ([]byte, []int) {
	return file_skill_proto_rawDescGZIP(), []int{3}
}

func (x *SkillCollectionActivateResp) GetCollection() *SkillCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

var File_skill_proto protoreflect.FileDescriptor

var file_skill_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x6b, 0x69, 0x6c, 0x6c, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x05, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x1b, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x6c, 0x6f,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x5f, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0d, 0x72, 0x65, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x87, 0x01, 0x0a,
	0x0f, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x3a, 0x0a,
	0x10, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4b, 0x56, 0x52, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x78, 0x0a, 0x1a, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x66, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x55, 0x0a, 0x1b, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x36, 0x0a, 0x0a, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x2e, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x29, 0x5a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_skill_proto_rawDescOnce sync.Once
	file_skill_proto_rawDescData = file_skill_proto_rawDesc
)

func file_skill_proto_rawDescGZIP() []byte {
	file_skill_proto_rawDescOnce.Do(func() {
		file_skill_proto_rawDescData = protoimpl.X.CompressGZIP(file_skill_proto_rawDescData)
	})
	return file_skill_proto_rawDescData
}

var file_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_skill_proto_goTypes = []any{
	(*Skill)(nil),                       // 0: skill.Skill
	(*SkillCollection)(nil),             // 1: skill.SkillCollection
	(*SkillCollectionActivateReq)(nil),  // 2: skill.SkillCollectionActivateReq
	(*SkillCollectionActivateResp)(nil), // 3: skill.SkillCollectionActivateResp
	(*pb_common.Int32KV)(nil),           // 4: common.Int32KV
}
var file_skill_proto_depIdxs = []int32{
	4, // 0: skill.SkillCollection.collection_level:type_name -> common.Int32KV
	1, // 1: skill.SkillCollectionActivateResp.collection:type_name -> skill.SkillCollection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_skill_proto_init() }
func file_skill_proto_init() {
	if File_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_skill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_skill_proto_goTypes,
		DependencyIndexes: file_skill_proto_depIdxs,
		MessageInfos:      file_skill_proto_msgTypes,
	}.Build()
	File_skill_proto = out.File
	file_skill_proto_rawDesc = nil
	file_skill_proto_goTypes = nil
	file_skill_proto_depIdxs = nil
}
