// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: equip.proto

package pb_equip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Weapon 宝物
type Weapon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId int32 `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"` // 配置id
	SlotId   int32 `protobuf:"varint,2,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`       // 槽位
	Level    int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                       // 技能等级
}

func (x *Weapon) Reset() {
	*x = Weapon{}
	mi := &file_equip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weapon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weapon) ProtoMessage() {}

func (x *Weapon) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weapon.ProtoReflect.Descriptor instead.
func (*Weapon) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{0}
}

func (x *Weapon) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *Weapon) GetSlotId() int32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *Weapon) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Troop 兵种
type Troop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId           int32 `protobuf:"varint,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`                                    // 配置id
	IsActivate         bool  `protobuf:"varint,2,opt,name=is_activate,json=isActivate,proto3" json:"is_activate,omitempty"`                              // 是否已经激活
	ExAbilityConfigId1 int32 `protobuf:"varint,11,opt,name=ex_ability_config_id1,json=exAbilityConfigId1,proto3" json:"ex_ability_config_id1,omitempty"` // 额外能力1
	ExAbilityConfigId2 int32 `protobuf:"varint,12,opt,name=ex_ability_config_id2,json=exAbilityConfigId2,proto3" json:"ex_ability_config_id2,omitempty"` // 额外能力2
}

func (x *Troop) Reset() {
	*x = Troop{}
	mi := &file_equip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Troop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Troop) ProtoMessage() {}

func (x *Troop) ProtoReflect() protoreflect.Message {
	mi := &file_equip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Troop.ProtoReflect.Descriptor instead.
func (*Troop) Descriptor() ([]byte, []int) {
	return file_equip_proto_rawDescGZIP(), []int{1}
}

func (x *Troop) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *Troop) GetIsActivate() bool {
	if x != nil {
		return x.IsActivate
	}
	return false
}

func (x *Troop) GetExAbilityConfigId1() int32 {
	if x != nil {
		return x.ExAbilityConfigId1
	}
	return 0
}

func (x *Troop) GetExAbilityConfigId2() int32 {
	if x != nil {
		return x.ExAbilityConfigId2
	}
	return 0
}

var File_equip_proto protoreflect.FileDescriptor

var file_equip_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x22, 0x54, 0x0a, 0x06, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x6c, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6c,
	0x6f, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0xab, 0x01, 0x0a, 0x05, 0x54,
	0x72, 0x6f, 0x6f, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x12, 0x31, 0x0a, 0x15, 0x65, 0x78, 0x5f, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x31, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x12, 0x65, 0x78, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x49, 0x64, 0x31, 0x12, 0x31, 0x0a, 0x15, 0x65, 0x78, 0x5f, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x32, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x12, 0x65, 0x78, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x32, 0x42, 0x29, 0x5a, 0x27, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x73, 0x6c, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_equip_proto_rawDescOnce sync.Once
	file_equip_proto_rawDescData = file_equip_proto_rawDesc
)

func file_equip_proto_rawDescGZIP() []byte {
	file_equip_proto_rawDescOnce.Do(func() {
		file_equip_proto_rawDescData = protoimpl.X.CompressGZIP(file_equip_proto_rawDescData)
	})
	return file_equip_proto_rawDescData
}

var file_equip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_equip_proto_goTypes = []any{
	(*Weapon)(nil), // 0: equip.Weapon
	(*Troop)(nil),  // 1: equip.Troop
}
var file_equip_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_equip_proto_init() }
func file_equip_proto_init() {
	if File_equip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_equip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_equip_proto_goTypes,
		DependencyIndexes: file_equip_proto_depIdxs,
		MessageInfos:      file_equip_proto_msgTypes,
	}.Build()
	File_equip_proto = out.File
	file_equip_proto_rawDesc = nil
	file_equip_proto_goTypes = nil
	file_equip_proto_depIdxs = nil
}
