// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: union.proto

package pb_union

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 联盟职位
type UnionPosition int32

const (
	UnionPosition_UNION_POSITION_NONE    UnionPosition = 0 // 无/未知
	UnionPosition_UNION_POSITION_LEADER  UnionPosition = 1 // 盟主
	UnionPosition_UNION_POSITION_OFFICER UnionPosition = 2 // 官员
	UnionPosition_UNION_POSITION_MEMBER  UnionPosition = 3 // 成员
)

// Enum value maps for UnionPosition.
var (
	UnionPosition_name = map[int32]string{
		0: "UNION_POSITION_NONE",
		1: "UNION_POSITION_LEADER",
		2: "UNION_POSITION_OFFICER",
		3: "UNION_POSITION_MEMBER",
	}
	UnionPosition_value = map[string]int32{
		"UNION_POSITION_NONE":    0,
		"UNION_POSITION_LEADER":  1,
		"UNION_POSITION_OFFICER": 2,
		"UNION_POSITION_MEMBER":  3,
	}
)

func (x UnionPosition) Enum() *UnionPosition {
	p := new(UnionPosition)
	*p = x
	return p
}

func (x UnionPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnionPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_union_proto_enumTypes[0].Descriptor()
}

func (UnionPosition) Type() protoreflect.EnumType {
	return &file_union_proto_enumTypes[0]
}

func (x UnionPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnionPosition.Descriptor instead.
func (UnionPosition) EnumDescriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{0}
}

// UnionBrief 联盟简要信息（角色侧快照 / 列表展示）
type UnionBrief struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId     uint64 `protobuf:"varint,1,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LeaderId    uint64 `protobuf:"varint,3,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`          // 盟主角色ID
	MemberCount uint32 `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"` // 成员数
	Notice      string `protobuf:"bytes,5,opt,name=notice,proto3" json:"notice,omitempty"`                               // 公告
}

func (x *UnionBrief) Reset() {
	*x = UnionBrief{}
	mi := &file_union_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionBrief) ProtoMessage() {}

func (x *UnionBrief) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionBrief.ProtoReflect.Descriptor instead.
func (*UnionBrief) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{0}
}

func (x *UnionBrief) GetUnionId() uint64 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

func (x *UnionBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UnionBrief) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *UnionBrief) GetMemberCount() uint32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *UnionBrief) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

// RoleUnionInfo 角色侧联盟信息（role_union 快照，含额外信息）
type RoleUnionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brief    *UnionBrief `protobuf:"bytes,1,opt,name=brief,proto3" json:"brief,omitempty"`                  // union proto 简要信息
	Position int32       `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`           // 职位（UnionPosition）
	JoinUx   int64       `protobuf:"varint,3,opt,name=join_ux,json=joinUx,proto3" json:"join_ux,omitempty"` // 加入时间
}

func (x *RoleUnionInfo) Reset() {
	*x = RoleUnionInfo{}
	mi := &file_union_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleUnionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleUnionInfo) ProtoMessage() {}

func (x *RoleUnionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleUnionInfo.ProtoReflect.Descriptor instead.
func (*RoleUnionInfo) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{1}
}

func (x *RoleUnionInfo) GetBrief() *UnionBrief {
	if x != nil {
		return x.Brief
	}
	return nil
}

func (x *RoleUnionInfo) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RoleUnionInfo) GetJoinUx() int64 {
	if x != nil {
		return x.JoinUx
	}
	return 0
}

// UnionMember 联盟成员
type UnionMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId   uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Position int32  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`                // 职位（UnionPosition）
	RoleName string `protobuf:"bytes,3,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"` // 角色名（简要）
	Level    int32  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                      // 角色/英雄等级（简要）
}

func (x *UnionMember) Reset() {
	*x = UnionMember{}
	mi := &file_union_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionMember) ProtoMessage() {}

func (x *UnionMember) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionMember.ProtoReflect.Descriptor instead.
func (*UnionMember) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{2}
}

func (x *UnionMember) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UnionMember) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *UnionMember) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UnionMember) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// UnionInfo 完整联盟信息
type UnionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brief   *UnionBrief    `protobuf:"bytes,1,opt,name=brief,proto3" json:"brief,omitempty"`
	Members []*UnionMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *UnionInfo) Reset() {
	*x = UnionInfo{}
	mi := &file_union_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionInfo) ProtoMessage() {}

func (x *UnionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionInfo.ProtoReflect.Descriptor instead.
func (*UnionInfo) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{3}
}

func (x *UnionInfo) GetBrief() *UnionBrief {
	if x != nil {
		return x.Brief
	}
	return nil
}

func (x *UnionInfo) GetMembers() []*UnionMember {
	if x != nil {
		return x.Members
	}
	return nil
}

// ---- 建盟 ----
type UnionCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 联盟名（服内唯一）
}

func (x *UnionCreateReq) Reset() {
	*x = UnionCreateReq{}
	mi := &file_union_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionCreateReq) ProtoMessage() {}

func (x *UnionCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionCreateReq.ProtoReflect.Descriptor instead.
func (*UnionCreateReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{4}
}

func (x *UnionCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnionCreateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleUnion *RoleUnionInfo `protobuf:"bytes,1,opt,name=role_union,json=roleUnion,proto3" json:"role_union,omitempty"` // 建盟后角色侧联盟快照
}

func (x *UnionCreateResp) Reset() {
	*x = UnionCreateResp{}
	mi := &file_union_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionCreateResp) ProtoMessage() {}

func (x *UnionCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionCreateResp.ProtoReflect.Descriptor instead.
func (*UnionCreateResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{5}
}

func (x *UnionCreateResp) GetRoleUnion() *RoleUnionInfo {
	if x != nil {
		return x.RoleUnion
	}
	return nil
}

// ---- 加入 ----
type UnionJoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId uint64 `protobuf:"varint,1,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
}

func (x *UnionJoinReq) Reset() {
	*x = UnionJoinReq{}
	mi := &file_union_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionJoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionJoinReq) ProtoMessage() {}

func (x *UnionJoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionJoinReq.ProtoReflect.Descriptor instead.
func (*UnionJoinReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{6}
}

func (x *UnionJoinReq) GetUnionId() uint64 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

type UnionJoinResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleUnion *RoleUnionInfo `protobuf:"bytes,1,opt,name=role_union,json=roleUnion,proto3" json:"role_union,omitempty"`
}

func (x *UnionJoinResp) Reset() {
	*x = UnionJoinResp{}
	mi := &file_union_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionJoinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionJoinResp) ProtoMessage() {}

func (x *UnionJoinResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionJoinResp.ProtoReflect.Descriptor instead.
func (*UnionJoinResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{7}
}

func (x *UnionJoinResp) GetRoleUnion() *RoleUnionInfo {
	if x != nil {
		return x.RoleUnion
	}
	return nil
}

// ---- 退出 ----
type UnionLeaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnionLeaveReq) Reset() {
	*x = UnionLeaveReq{}
	mi := &file_union_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionLeaveReq) ProtoMessage() {}

func (x *UnionLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionLeaveReq.ProtoReflect.Descriptor instead.
func (*UnionLeaveReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{8}
}

type UnionLeaveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnionLeaveResp) Reset() {
	*x = UnionLeaveResp{}
	mi := &file_union_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionLeaveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionLeaveResp) ProtoMessage() {}

func (x *UnionLeaveResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionLeaveResp.ProtoReflect.Descriptor instead.
func (*UnionLeaveResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{9}
}

// ---- 踢人 ----
type UnionKickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 被踢角色
}

func (x *UnionKickReq) Reset() {
	*x = UnionKickReq{}
	mi := &file_union_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionKickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionKickReq) ProtoMessage() {}

func (x *UnionKickReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionKickReq.ProtoReflect.Descriptor instead.
func (*UnionKickReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{10}
}

func (x *UnionKickReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UnionKickResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnionKickResp) Reset() {
	*x = UnionKickResp{}
	mi := &file_union_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionKickResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionKickResp) ProtoMessage() {}

func (x *UnionKickResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionKickResp.ProtoReflect.Descriptor instead.
func (*UnionKickResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{11}
}

// ---- 转让盟主 ----
type UnionTransferReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleId uint64 `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"` // 新盟主
}

func (x *UnionTransferReq) Reset() {
	*x = UnionTransferReq{}
	mi := &file_union_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionTransferReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionTransferReq) ProtoMessage() {}

func (x *UnionTransferReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionTransferReq.ProtoReflect.Descriptor instead.
func (*UnionTransferReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{12}
}

func (x *UnionTransferReq) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type UnionTransferResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnionTransferResp) Reset() {
	*x = UnionTransferResp{}
	mi := &file_union_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionTransferResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionTransferResp) ProtoMessage() {}

func (x *UnionTransferResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionTransferResp.ProtoReflect.Descriptor instead.
func (*UnionTransferResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{13}
}

// ---- 解散 ----
type UnionDissolveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnionDissolveReq) Reset() {
	*x = UnionDissolveReq{}
	mi := &file_union_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionDissolveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionDissolveReq) ProtoMessage() {}

func (x *UnionDissolveReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionDissolveReq.ProtoReflect.Descriptor instead.
func (*UnionDissolveReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{14}
}

type UnionDissolveResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnionDissolveResp) Reset() {
	*x = UnionDissolveResp{}
	mi := &file_union_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionDissolveResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionDissolveResp) ProtoMessage() {}

func (x *UnionDissolveResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionDissolveResp.ProtoReflect.Descriptor instead.
func (*UnionDissolveResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{15}
}

// ---- 查询 ----
type UnionInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnionId uint64 `protobuf:"varint,1,opt,name=union_id,json=unionId,proto3" json:"union_id,omitempty"`
}

func (x *UnionInfoReq) Reset() {
	*x = UnionInfoReq{}
	mi := &file_union_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionInfoReq) ProtoMessage() {}

func (x *UnionInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionInfoReq.ProtoReflect.Descriptor instead.
func (*UnionInfoReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{16}
}

func (x *UnionInfoReq) GetUnionId() uint64 {
	if x != nil {
		return x.UnionId
	}
	return 0
}

type UnionInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Union *UnionInfo `protobuf:"bytes,1,opt,name=union,proto3" json:"union,omitempty"`
}

func (x *UnionInfoResp) Reset() {
	*x = UnionInfoResp{}
	mi := &file_union_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionInfoResp) ProtoMessage() {}

func (x *UnionInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionInfoResp.ProtoReflect.Descriptor instead.
func (*UnionInfoResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{17}
}

func (x *UnionInfoResp) GetUnion() *UnionInfo {
	if x != nil {
		return x.Union
	}
	return nil
}

type UnionMemberListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnionMemberListReq) Reset() {
	*x = UnionMemberListReq{}
	mi := &file_union_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionMemberListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionMemberListReq) ProtoMessage() {}

func (x *UnionMemberListReq) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionMemberListReq.ProtoReflect.Descriptor instead.
func (*UnionMemberListReq) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{18}
}

type UnionMemberListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members []*UnionMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *UnionMemberListResp) Reset() {
	*x = UnionMemberListResp{}
	mi := &file_union_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnionMemberListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnionMemberListResp) ProtoMessage() {}

func (x *UnionMemberListResp) ProtoReflect() protoreflect.Message {
	mi := &file_union_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnionMemberListResp.ProtoReflect.Descriptor instead.
func (*UnionMemberListResp) Descriptor() ([]byte, []int) {
	return file_union_proto_rawDescGZIP(), []int{19}
}

func (x *UnionMemberListResp) GetMembers() []*UnionMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_union_proto protoreflect.FileDescriptor

var file_union_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x0a, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x42, 0x72,
	0x69, 0x65, 0x66, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x22, 0x6d, 0x0a, 0x0d, 0x52, 0x6f,
	0x6c, 0x65, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a, 0x05, 0x62,
	0x72, 0x69, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x6e, 0x69,
	0x6f, 0x6e, 0x2e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52, 0x05, 0x62,
	0x72, 0x69, 0x65, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x17, 0x0a, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x75, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x6a, 0x6f, 0x69, 0x6e, 0x55, 0x78, 0x22, 0x75, 0x0a, 0x0b, 0x55, 0x6e, 0x69,
	0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0x62, 0x0a, 0x09, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x27, 0x0a,
	0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52,
	0x05, 0x62, 0x72, 0x69, 0x65, 0x66, 0x12, 0x2c, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e,
	0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x0f, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a,
	0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x55, 0x6e, 0x69,
	0x6f, 0x6e, 0x22, 0x29, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x44, 0x0a,
	0x0d, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33,
	0x0a, 0x0a, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x27, 0x0a, 0x0c, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4b,
	0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22,
	0x0f, 0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x22, 0x2b, 0x0a, 0x10, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x13, 0x0a,
	0x11, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x12, 0x0a, 0x10, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x44, 0x69, 0x73, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x52, 0x65, 0x71, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x44,
	0x69, 0x73, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x29, 0x0a, 0x0c, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x75,
	0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0d, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x55,
	0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x22,
	0x14, 0x0a, 0x12, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x22, 0x43, 0x0a, 0x13, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x07,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x75, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2a, 0x7a, 0x0a, 0x0d, 0x55, 0x6e,
	0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x55,
	0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f,
	0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12,
	0x1a, 0x0a, 0x16, 0x55, 0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x4f, 0x46, 0x46, 0x49, 0x43, 0x45, 0x52, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x55,
	0x4e, 0x49, 0x4f, 0x4e, 0x5f, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x45,
	0x4d, 0x42, 0x45, 0x52, 0x10, 0x03, 0x42, 0x29, 0x5a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x73, 0x6c, 0x67, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x75, 0x6e, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_union_proto_rawDescOnce sync.Once
	file_union_proto_rawDescData = file_union_proto_rawDesc
)

func file_union_proto_rawDescGZIP() []byte {
	file_union_proto_rawDescOnce.Do(func() {
		file_union_proto_rawDescData = protoimpl.X.CompressGZIP(file_union_proto_rawDescData)
	})
	return file_union_proto_rawDescData
}

var file_union_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_union_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_union_proto_goTypes = []any{
	(UnionPosition)(0),          // 0: union.UnionPosition
	(*UnionBrief)(nil),          // 1: union.UnionBrief
	(*RoleUnionInfo)(nil),       // 2: union.RoleUnionInfo
	(*UnionMember)(nil),         // 3: union.UnionMember
	(*UnionInfo)(nil),           // 4: union.UnionInfo
	(*UnionCreateReq)(nil),      // 5: union.UnionCreateReq
	(*UnionCreateResp)(nil),     // 6: union.UnionCreateResp
	(*UnionJoinReq)(nil),        // 7: union.UnionJoinReq
	(*UnionJoinResp)(nil),       // 8: union.UnionJoinResp
	(*UnionLeaveReq)(nil),       // 9: union.UnionLeaveReq
	(*UnionLeaveResp)(nil),      // 10: union.UnionLeaveResp
	(*UnionKickReq)(nil),        // 11: union.UnionKickReq
	(*UnionKickResp)(nil),       // 12: union.UnionKickResp
	(*UnionTransferReq)(nil),    // 13: union.UnionTransferReq
	(*UnionTransferResp)(nil),   // 14: union.UnionTransferResp
	(*UnionDissolveReq)(nil),    // 15: union.UnionDissolveReq
	(*UnionDissolveResp)(nil),   // 16: union.UnionDissolveResp
	(*UnionInfoReq)(nil),        // 17: union.UnionInfoReq
	(*UnionInfoResp)(nil),       // 18: union.UnionInfoResp
	(*UnionMemberListReq)(nil),  // 19: union.UnionMemberListReq
	(*UnionMemberListResp)(nil), // 20: union.UnionMemberListResp
}
var file_union_proto_depIdxs = []int32{
	1, // 0: union.RoleUnionInfo.brief:type_name -> union.UnionBrief
	1, // 1: union.UnionInfo.brief:type_name -> union.UnionBrief
	3, // 2: union.UnionInfo.members:type_name -> union.UnionMember
	2, // 3: union.UnionCreateResp.role_union:type_name -> union.RoleUnionInfo
	2, // 4: union.UnionJoinResp.role_union:type_name -> union.RoleUnionInfo
	4, // 5: union.UnionInfoResp.union:type_name -> union.UnionInfo
	3, // 6: union.UnionMemberListResp.members:type_name -> union.UnionMember
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_union_proto_init() }
func file_union_proto_init() {
	if File_union_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_union_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_union_proto_goTypes,
		DependencyIndexes: file_union_proto_depIdxs,
		EnumInfos:         file_union_proto_enumTypes,
		MessageInfos:      file_union_proto_msgTypes,
	}.Build()
	File_union_proto = out.File
	file_union_proto_rawDesc = nil
	file_union_proto_goTypes = nil
	file_union_proto_depIdxs = nil
}
