// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: services/gate_server.proto

package pb_gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GatewayService_Stream_FullMethodName = "/pb_gateway.GatewayService/Stream"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (GatewayService_StreamClient, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (GatewayService_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_Stream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayServiceStreamClient{stream}
	return x, nil
}

type GatewayService_StreamClient interface {
	Send(*pb_common.NodePacket) error
	Recv() (*pb_common.NodePacket, error)
	grpc.ClientStream
}

type gatewayServiceStreamClient struct {
	grpc.ClientStream
}

func (x *gatewayServiceStreamClient) Send(m *pb_common.NodePacket) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayServiceStreamClient) Recv() (*pb_common.NodePacket, error) {
	m := new(pb_common.NodePacket)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility
type GatewayServiceServer interface {
	Stream(GatewayService_StreamServer) error
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServiceServer struct {
}

func (UnimplementedGatewayServiceServer) Stream(GatewayService_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServiceServer).Stream(&gatewayServiceStreamServer{stream})
}

type GatewayService_StreamServer interface {
	Send(*pb_common.NodePacket) error
	Recv() (*pb_common.NodePacket, error)
	grpc.ServerStream
}

type gatewayServiceStreamServer struct {
	grpc.ServerStream
}

func (x *gatewayServiceStreamServer) Send(m *pb_common.NodePacket) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayServiceStreamServer) Recv() (*pb_common.NodePacket, error) {
	m := new(pb_common.NodePacket)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _GatewayService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/gate_server.proto",
}

const (
	GatewayHandler_NotifyInfo_FullMethodName = "/pb_gateway.GatewayHandler/NotifyInfo"
)

// GatewayHandlerClient is the client API for GatewayHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayHandlerClient interface {
	// 登录服创建玩家
	NotifyInfo(ctx context.Context, in *pb_common.NotifyInfoReq, opts ...grpc.CallOption) (*pb_common.NotifyInfoRsp, error)
}

type gatewayHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayHandlerClient(cc grpc.ClientConnInterface) GatewayHandlerClient {
	return &gatewayHandlerClient{cc}
}

func (c *gatewayHandlerClient) NotifyInfo(ctx context.Context, in *pb_common.NotifyInfoReq, opts ...grpc.CallOption) (*pb_common.NotifyInfoRsp, error) {
	out := new(pb_common.NotifyInfoRsp)
	err := c.cc.Invoke(ctx, GatewayHandler_NotifyInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayHandlerServer is the server API for GatewayHandler service.
// All implementations must embed UnimplementedGatewayHandlerServer
// for forward compatibility
type GatewayHandlerServer interface {
	// 登录服创建玩家
	NotifyInfo(context.Context, *pb_common.NotifyInfoReq) (*pb_common.NotifyInfoRsp, error)
	mustEmbedUnimplementedGatewayHandlerServer()
}

// UnimplementedGatewayHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayHandlerServer struct {
}

func (UnimplementedGatewayHandlerServer) NotifyInfo(context.Context, *pb_common.NotifyInfoReq) (*pb_common.NotifyInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyInfo not implemented")
}
func (UnimplementedGatewayHandlerServer) mustEmbedUnimplementedGatewayHandlerServer() {}

// UnsafeGatewayHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayHandlerServer will
// result in compilation errors.
type UnsafeGatewayHandlerServer interface {
	mustEmbedUnimplementedGatewayHandlerServer()
}

func RegisterGatewayHandlerServer(s grpc.ServiceRegistrar, srv GatewayHandlerServer) {
	s.RegisterService(&GatewayHandler_ServiceDesc, srv)
}

func _GatewayHandler_NotifyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.NotifyInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayHandlerServer).NotifyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayHandler_NotifyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayHandlerServer).NotifyInfo(ctx, req.(*pb_common.NotifyInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayHandler_ServiceDesc is the grpc.ServiceDesc for GatewayHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_gateway.GatewayHandler",
	HandlerType: (*GatewayHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyInfo",
			Handler:    _GatewayHandler_NotifyInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/gate_server.proto",
}
