// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.8
// source: services/gate_server.proto

package pb_gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GatewayNodeService_NotifyInfo_FullMethodName = "/pb_gateway.GatewayNodeService/NotifyInfo"
)

// GatewayNodeServiceClient is the client API for GatewayNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayNodeServiceClient interface {
	// 登录服创建玩家
	NotifyInfo(ctx context.Context, in *pb_common.NotifyInfoReq, opts ...grpc.CallOption) (*pb_common.NotifyInfoRsp, error)
}

type gatewayNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayNodeServiceClient(cc grpc.ClientConnInterface) GatewayNodeServiceClient {
	return &gatewayNodeServiceClient{cc}
}

func (c *gatewayNodeServiceClient) NotifyInfo(ctx context.Context, in *pb_common.NotifyInfoReq, opts ...grpc.CallOption) (*pb_common.NotifyInfoRsp, error) {
	out := new(pb_common.NotifyInfoRsp)
	err := c.cc.Invoke(ctx, GatewayNodeService_NotifyInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayNodeServiceServer is the server API for GatewayNodeService service.
// All implementations must embed UnimplementedGatewayNodeServiceServer
// for forward compatibility
type GatewayNodeServiceServer interface {
	// 登录服创建玩家
	NotifyInfo(context.Context, *pb_common.NotifyInfoReq) (*pb_common.NotifyInfoRsp, error)
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

// UnimplementedGatewayNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayNodeServiceServer struct {
}

func (UnimplementedGatewayNodeServiceServer) NotifyInfo(context.Context, *pb_common.NotifyInfoReq) (*pb_common.NotifyInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyInfo not implemented")
}
func (UnimplementedGatewayNodeServiceServer) mustEmbedUnimplementedGatewayNodeServiceServer() {}

// UnsafeGatewayNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayNodeServiceServer will
// result in compilation errors.
type UnsafeGatewayNodeServiceServer interface {
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

func RegisterGatewayNodeServiceServer(s grpc.ServiceRegistrar, srv GatewayNodeServiceServer) {
	s.RegisterService(&GatewayNodeService_ServiceDesc, srv)
}

func _GatewayNodeService_NotifyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.NotifyInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNodeServiceServer).NotifyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNodeService_NotifyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNodeServiceServer).NotifyInfo(ctx, req.(*pb_common.NotifyInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayNodeService_ServiceDesc is the grpc.ServiceDesc for GatewayNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_gateway.GatewayNodeService",
	HandlerType: (*GatewayNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyInfo",
			Handler:    _GatewayNodeService_NotifyInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/gate_server.proto",
}
