// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: services/gate_server.proto

package pb_gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	pb_common "server.slg.com/api/protocol/pb/pb_common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayNodeService_NotifyInfo_FullMethodName = "/pb_gateway.GatewayNodeService/NotifyInfo"
)

// GatewayNodeServiceClient is the client API for GatewayNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayNodeServiceClient interface {
	// 登录服创建玩家
	NotifyInfo(ctx context.Context, in *pb_common.NotifyInfoReq, opts ...grpc.CallOption) (*pb_common.NotifyInfoRsp, error)
}

type gatewayNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayNodeServiceClient(cc grpc.ClientConnInterface) GatewayNodeServiceClient {
	return &gatewayNodeServiceClient{cc}
}

func (c *gatewayNodeServiceClient) NotifyInfo(ctx context.Context, in *pb_common.NotifyInfoReq, opts ...grpc.CallOption) (*pb_common.NotifyInfoRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(pb_common.NotifyInfoRsp)
	err := c.cc.Invoke(ctx, GatewayNodeService_NotifyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayNodeServiceServer is the server API for GatewayNodeService service.
// All implementations must embed UnimplementedGatewayNodeServiceServer
// for forward compatibility.
type GatewayNodeServiceServer interface {
	// 登录服创建玩家
	NotifyInfo(context.Context, *pb_common.NotifyInfoReq) (*pb_common.NotifyInfoRsp, error)
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

// UnimplementedGatewayNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayNodeServiceServer struct{}

func (UnimplementedGatewayNodeServiceServer) NotifyInfo(context.Context, *pb_common.NotifyInfoReq) (*pb_common.NotifyInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyInfo not implemented")
}
func (UnimplementedGatewayNodeServiceServer) mustEmbedUnimplementedGatewayNodeServiceServer() {}
func (UnimplementedGatewayNodeServiceServer) testEmbeddedByValue()                            {}

// UnsafeGatewayNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayNodeServiceServer will
// result in compilation errors.
type UnsafeGatewayNodeServiceServer interface {
	mustEmbedUnimplementedGatewayNodeServiceServer()
}

func RegisterGatewayNodeServiceServer(s grpc.ServiceRegistrar, srv GatewayNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayNodeService_ServiceDesc, srv)
}

func _GatewayNodeService_NotifyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb_common.NotifyInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayNodeServiceServer).NotifyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayNodeService_NotifyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayNodeServiceServer).NotifyInfo(ctx, req.(*pb_common.NotifyInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayNodeService_ServiceDesc is the grpc.ServiceDesc for GatewayNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_gateway.GatewayNodeService",
	HandlerType: (*GatewayNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyInfo",
			Handler:    _GatewayNodeService_NotifyInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/gate_server.proto",
}
